/***************************************************************************
 *   Copyright 2019 by Davide Bettio <davide@uninstall.it>                 *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU Lesser General Public License as        *
 *   published by the Free Software Foundation; either version 2 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA .        *
 ***************************************************************************/

#ifndef _PLATFORM_DEFAULTATOMS_H_
#define _PLATFORM_DEFAULTATOMS_H_

#include "defaultatoms.h"

#define SET_LEVEL_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 0)
#define READ_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 1)
#define INPUT_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 2)
#define OUTPUT_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 3)
#define SET_DIRECTION_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 4)
#define SET_INT_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 5)
#define GPIO_INTERRUPT_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 6)
#define NONE_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 7)
#define RISING_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 8)
#define FALLING_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 9)
#define BOTH_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 10)
#define LOW_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 11)
#define HIGH_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 12)

#define SOCKET_ATOMS_BASE_INDEX (PLATFORM_ATOMS_BASE_INDEX + 13)
#define PROTO_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 0)
#define UDP_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 1)
#define TCP_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 2)
#define SOCKET_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 3)
#define FCNTL_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 4)
#define BIND_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 5)
#define GETSOCKNAME_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 6)
#define RECVFROM_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 7)
#define SENDTO_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 8)
#define ADDRESS_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 9)
#define PORT_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 10)
#define CONTROLLING_PROCESS_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 11)
#define BINARY_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 12)
#define ACTIVE_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 13)
#define BUFFER_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 14)
#define CONNECT_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 15)
#define SEND_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 16)
#define TCP_CLOSED_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 17)
#define RECV_ATOM_INDEX (SOCKET_ATOMS_BASE_INDEX + 18)

#define NETWORK_ATOMS_BASE_INDEX (SOCKET_ATOMS_BASE_INDEX + 19)
#define STA_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 0)
#define SSID_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 1)
#define PSK_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 2)
#define SNTP_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 3)
#define STA_GOT_IP_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 4)
#define STA_CONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 5)
#define STA_DISCONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 6)

#define SPIDRIVER_ATOMS_BASE_INDEX (NETWORK_ATOMS_BASE_INDEX + 7)
#define BUS_CONFIG_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 0)
#define MISO_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 1)
#define MOSI_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 2)
#define SCLK_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 3)
#define DEVICE_CONFIG_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 4)
#define SPI_CLOCK_HZ_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 5)
#define SPI_MODE_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 6)
#define SPI_CS_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 7)
#define ADDRESS_LEN_BITS_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 8)
#define READ_AT_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 9)
#define WRITE_AT_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 10)

#define I2CDRIVER_ATOMS_BASE_INDEX (WRITE_AT_ATOM_INDEX + 1)
#define BEGIN_TRANSMISSION_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 0)
#define END_TRANSMISSION_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 1)
#define WRITE_BYTE_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 2)
#define SCL_IO_NUM_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 3)
#define SDA_IO_NUM_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 4)
#define I2C_CLOCK_HZ_ATOM_INDEX (I2CDRIVER_ATOMS_BASE_INDEX + 5)

#define ADDRESS_ATOM term_from_atom_index(ADDRESS_ATOM_INDEX)
#define PORT_ATOM term_from_atom_index(PORT_ATOM_INDEX)
#define CONTROLLING_PROCESS_ATOM term_from_atom_index(CONTROLLING_PROCESS_ATOM_INDEX)
#define BINARY_ATOM term_from_atom_index(BINARY_ATOM_INDEX)
#define ACTIVE_ATOM term_from_atom_index(ACTIVE_ATOM_INDEX)
#define BUFFER_ATOM term_from_atom_index(BUFFER_ATOM_INDEX)

#define SET_LEVEL_ATOM TERM_FROM_ATOM_INDEX(SET_LEVEL_ATOM_INDEX)
#define READ_ATOM TERM_FROM_ATOM_INDEX(READ_ATOM_INDEX)
#define INPUT_ATOM TERM_FROM_ATOM_INDEX(INPUT_ATOM_INDEX)
#define OUTPUT_ATOM TERM_FROM_ATOM_INDEX(OUTPUT_ATOM_INDEX)
#define SET_DIRECTION_ATOM TERM_FROM_ATOM_INDEX(SET_DIRECTION_ATOM_INDEX)
#define SET_INT_ATOM TERM_FROM_ATOM_INDEX(SET_INT_ATOM_INDEX)
#define GPIO_INTERRUPT_ATOM TERM_FROM_ATOM_INDEX(GPIO_INTERRUPT_ATOM_INDEX)
#define NONE_ATOM TERM_FROM_ATOM_INDEX(NONE_ATOM_INDEX)
#define RISING_ATOM TERM_FROM_ATOM_INDEX(RISING_ATOM_INDEX)
#define FALLING_ATOM TERM_FROM_ATOM_INDEX(FALLING_ATOM_INDEX)
#define BOTH_ATOM TERM_FROM_ATOM_INDEX(BOTH_ATOM_INDEX)
#define LOW_ATOM TERM_FROM_ATOM_INDEX(LOW_ATOM_INDEX)
#define HIGH_ATOM TERM_FROM_ATOM_INDEX(HIGH_ATOM_INDEX)

// socket
#define PROTO_ATOM TERM_FROM_ATOM_INDEX(PROTO_ATOM_INDEX)
#define UDP_ATOM TERM_FROM_ATOM_INDEX(UDP_ATOM_INDEX)
#define TCP_ATOM TERM_FROM_ATOM_INDEX(TCP_ATOM_INDEX)
#define SOCKET_ATOM TERM_FROM_ATOM_INDEX(SOCKET_ATOM_INDEX)
#define FCNTL_ATOM TERM_FROM_ATOM_INDEX(FCNTL_ATOM_INDEX)
#define BIND_ATOM TERM_FROM_ATOM_INDEX(BIND_ATOM_INDEX)
#define GETSOCKNAME_ATOM TERM_FROM_ATOM_INDEX(GETSOCKNAME_ATOM_INDEX)
#define RECVFROM_ATOM TERM_FROM_ATOM_INDEX(RECVFROM_ATOM_INDEX)
#define SENDTO_ATOM TERM_FROM_ATOM_INDEX(SENDTO_ATOM_INDEX)
#define ADDRESS_ATOM term_from_atom_index(ADDRESS_ATOM_INDEX)
#define PORT_ATOM term_from_atom_index(PORT_ATOM_INDEX)
#define CONTROLLING_PROCESS_ATOM term_from_atom_index(CONTROLLING_PROCESS_ATOM_INDEX)
#define BINARY_ATOM term_from_atom_index(BINARY_ATOM_INDEX)
#define ACTIVE_ATOM term_from_atom_index(ACTIVE_ATOM_INDEX)
#define BUFFER_ATOM term_from_atom_index(BUFFER_ATOM_INDEX)
#define CONNECT_ATOM term_from_atom_index(CONNECT_ATOM_INDEX)
#define SEND_ATOM TERM_FROM_ATOM_INDEX(SEND_ATOM_INDEX)
#define TCP_CLOSED_ATOM TERM_FROM_ATOM_INDEX(TCP_CLOSED_ATOM_INDEX)
#define RECV_ATOM TERM_FROM_ATOM_INDEX(RECV_ATOM_INDEX)

// network
#define STA_ATOM TERM_FROM_ATOM_INDEX(STA_ATOM_INDEX)
#define SSID_ATOM TERM_FROM_ATOM_INDEX(SSID_ATOM_INDEX)
#define PSK_ATOM TERM_FROM_ATOM_INDEX(PSK_ATOM_INDEX)
#define SNTP_ATOM TERM_FROM_ATOM_INDEX(SNTP_ATOM_INDEX)
#define STA_GOT_IP_ATOM TERM_FROM_ATOM_INDEX(STA_GOT_IP_ATOM_INDEX)
#define STA_CONNECTED_ATOM TERM_FROM_ATOM_INDEX(STA_CONNECTED_ATOM_INDEX)
#define STA_DISCONNECTED_ATOM TERM_FROM_ATOM_INDEX(STA_DISCONNECTED_ATOM_INDEX)

//spidriver
#define BUS_CONFIG_ATOM TERM_FROM_ATOM_INDEX(BUS_CONFIG_ATOM_INDEX)
#define MISO_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(MISO_IO_NUM_ATOM_INDEX)
#define MOSI_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(MOSI_IO_NUM_ATOM_INDEX)
#define SCLK_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SCLK_IO_NUM_ATOM_INDEX)
#define DEVICE_CONFIG_ATOM TERM_FROM_ATOM_INDEX(DEVICE_CONFIG_ATOM_INDEX)
#define SPI_CLOCK_HZ_ATOM TERM_FROM_ATOM_INDEX(SPI_CLOCK_HZ_ATOM_INDEX)
#define SPI_MODE_ATOM TERM_FROM_ATOM_INDEX(SPI_MODE_ATOM_INDEX)
#define SPI_CS_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SPI_CS_IO_NUM_ATOM_INDEX)
#define ADDRESS_LEN_BITS_ATOM TERM_FROM_ATOM_INDEX(ADDRESS_LEN_BITS_ATOM_INDEX)
#define READ_AT_ATOM TERM_FROM_ATOM_INDEX(READ_AT_ATOM_INDEX)
#define WRITE_AT_ATOM TERM_FROM_ATOM_INDEX(WRITE_AT_ATOM_INDEX)

//i2cdriver
#define BEGIN_TRANSMISSION_ATOM TERM_FROM_ATOM_INDEX(BEGIN_TRANSMISSION_ATOM_INDEX)
#define END_TRANSMISSION_ATOM TERM_FROM_ATOM_INDEX(END_TRANSMISSION_ATOM_INDEX)
#define WRITE_BYTE_ATOM TERM_FROM_ATOM_INDEX(WRITE_BYTE_ATOM_INDEX)
#define SCL_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SCL_IO_NUM_ATOM_INDEX)
#define SDA_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SDA_IO_NUM_ATOM_INDEX)
#define I2C_CLOCK_HZ_ATOM TERM_FROM_ATOM_INDEX(I2C_CLOCK_HZ_ATOM_INDEX)

#endif
