%
%  This file is part of AtomVM.
%
%  Copyright 2016 Nicolas Seriot (JSONTestSuite test data, MIT license)
%  Copyright 2026 Davide Bettio <davide@uninstall.it>
%
%  Generated by generate_test_data.escript
%  Source: JSONTestSuite/test_parsing/
%
%  SPDX-License-Identifier: MIT
%
%  n_structure_100000_opening_arrays.json and n_structure_open_array_object.json
%  are tested as scaled-down equivalents (10K/5K depth) in test_deep_nesting/0.
%

-module(test_json).

-export([test/0]).

-include("etest.hrl").

test() ->
    ok = test_y(),
    ok = test_n(),
    ok = test_i(),
    ok = test_t(),
    ok = test_y_roundtrip(),
    ok = test_i_roundtrip(),
    ok = test_decode_basic(),
    ok = test_decode_strings(),
    ok = test_decode_containers(),
    ok = test_decode_whitespace(),
    ok = test_decode_errors(),
    ok = test_decode3(),
    ok = test_decode_streaming(),
    ok = test_decode_weather(),
    ok = test_decode_edge_cases(),
    ok = test_encode_basic(),
    ok = test_encode_strings(),
    ok = test_encode_arrays(),
    ok = test_encode_objects(),
    ok = test_encode_key_value_list(),
    ok = test_encode_checked(),
    ok = test_encode_errors(),
    ok = test_encode_custom_key_encoder(),
    ok = test_encode_checked_custom_key_encoder(),
    ok = test_roundtrip(),
    ok = test_streaming_splits(),
    ok = test_streaming_end_of_input(),
    ok = test_streaming_number_boundary(),
    ok = test_hex_error_classification(),
    ok = test_streaming_sliding_split(),
    ok = test_streaming_byte_by_byte(),
    ok = test_deep_nesting(),
    ok = test_encode_truncated_utf8(),
    ok = test_encode_checked_normalizing_encoder(),
    ok = test_encode_weather(),
    ok.

test_y() ->
    lists:foreach(fun run_y_test/1, y_tests()),
    ok.

test_n() ->
    lists:foreach(fun run_n_test/1, n_tests()),
    ok.

test_i() ->
    lists:foreach(fun run_i_test/1, i_tests()),
    ok.

test_t() ->
    lists:foreach(fun run_i_test/1, t_tests()),
    ok.

test_y_roundtrip() ->
    lists:foreach(fun run_y_roundtrip/1, y_tests()),
    ok.

test_i_roundtrip() ->
    lists:foreach(fun run_i_roundtrip/1, i_tests()),
    ok.

run_y_test({_Name, B64, Expected0}) ->
    Expected = resolve(Expected0),
    Expected = json:decode(base64:decode(B64)).

run_n_test({Name, B64, _}) ->
    Bin = base64:decode(B64),
    try json:decode(Bin) of
        Result -> error({should_have_failed, Name, Result})
    catch
        error:_ -> ok
    end.

run_i_test({Name, B64, Expected0}) ->
    case resolve(Expected0) of
        {ok, Expected} ->
            Expected = json:decode(base64:decode(B64));
        {error, _} ->
            Bin = base64:decode(B64),
            try json:decode(Bin) of
                Result -> error({should_have_failed, Name, Result})
            catch
                error:_ -> ok
            end
    end.

run_y_roundtrip({_Name, B64, Expected0}) ->
    Expected = resolve(Expected0),
    Decoded = json:decode(base64:decode(B64)),
    Decoded = json:decode(iolist_to_binary(json:encode(Expected))).

run_i_roundtrip({_Name, B64, Expected0}) ->
    case resolve(Expected0) of
        {ok, Expected} ->
            Decoded = json:decode(base64:decode(B64)),
            Decoded = json:decode(iolist_to_binary(json:encode(Expected)));
        {error, _} ->
            ok
    end.

resolve({external_term, Enc}) ->
    binary_to_term(base64:decode(Enc));
resolve(Term) ->
    Term.

to_bin(IoData) -> iolist_to_binary(IoData).

test_decode_basic() ->
    0 = json:decode(<<"0">>),
    1 = json:decode(<<"1">>),
    42 = json:decode(<<"42">>),
    123456789 = json:decode(<<"123456789">>),
    -1 = json:decode(<<"-1">>),
    -42 = json:decode(<<"-42">>),

    ?ASSERT_EQUALS(0.0, json:decode(<<"0.0">>)),
    ?ASSERT_EQUALS(3.14, json:decode(<<"3.14">>)),
    ?ASSERT_EQUALS(-2.5, json:decode(<<"-2.5">>)),
    ?ASSERT_EQUALS(0.1, json:decode(<<"0.1">>)),
    ?ASSERT_EQUALS(100.0, json:decode(<<"100.0">>)),

    ?ASSERT_EQUALS(1.0e5, json:decode(<<"1e5">>)),
    ?ASSERT_EQUALS(1.0e5, json:decode(<<"1E5">>)),
    ?ASSERT_EQUALS(1.0e5, json:decode(<<"1e+5">>)),
    ?ASSERT_EQUALS(1.0e-3, json:decode(<<"1e-3">>)),
    ?ASSERT_EQUALS(1.5e3, json:decode(<<"1.5e3">>)),
    ?ASSERT_EQUALS(1.5e-2, json:decode(<<"1.5e-2">>)),
    ?ASSERT_EQUALS(-1.0e5, json:decode(<<"-1e5">>)),
    ?ASSERT_EQUALS(-2.5e10, json:decode(<<"-2.5e10">>)),
    ?ASSERT_EQUALS(0.0e0, json:decode(<<"0e0">>)),
    ?ASSERT_EQUALS(0.0e0, json:decode(<<"0E0">>)),

    0 = json:decode(<<"-0">>),
    ?ASSERT_EQUALS(-0.0, json:decode(<<"-0.0">>)),

    true = json:decode(<<"true">>),
    false = json:decode(<<"false">>),
    null = json:decode(<<"null">>),
    ok.

test_decode_strings() ->
    <<>> = json:decode(<<"\"\"">>),
    <<"hello">> = json:decode(<<"\"hello\"">>),
    <<"hello world">> = json:decode(<<"\"hello world\"">>),

    <<"\"">> = json:decode(<<"\"\\\"\"">>),
    <<"\\">> = json:decode(<<"\"\\\\\"">>),
    <<"/">> = json:decode(<<"\"\\/\"">>),
    <<"\b">> = json:decode(<<"\"\\b\"">>),
    <<"\f">> = json:decode(<<"\"\\f\"">>),
    <<"\n">> = json:decode(<<"\"\\n\"">>),
    <<"\r">> = json:decode(<<"\"\\r\"">>),
    <<"\t">> = json:decode(<<"\"\\t\"">>),

    <<"hello\nworld">> = json:decode(<<"\"hello\\nworld\"">>),
    <<"\t\n\r">> = json:decode(<<"\"\\t\\n\\r\"">>),

    <<"A">> = json:decode(<<"\"\\u0041\"">>),
    <<16#C3, 16#A9>> = json:decode(<<"\"\\u00e9\"">>),
    <<16#C3, 16#A9>> = json:decode(<<"\"\\u00E9\"">>),
    <<0>> = json:decode(<<"\"\\u0000\"">>),
    <<16#E4, 16#B8, 16#96>> = json:decode(<<"\"\\u4e16\"">>),

    <<16#F0, 16#9F, 16#98, 16#80>> = json:decode(<<"\"\\uD83D\\uDE00\"">>),

    <<"A\nB">> = json:decode(<<"\"\\u0041\\nB\"">>),
    ok.

test_decode_containers() ->
    [] = json:decode(<<"[]">>),
    [1] = json:decode(<<"[1]">>),
    [1, 2, 3] = json:decode(<<"[1,2,3]">>),
    [1, <<"two">>, true, null] = json:decode(<<"[1, \"two\", true, null]">>),
    [[]] = json:decode(<<"[[]]">>),
    [[1, 2], [3, 4]] = json:decode(<<"[[1,2],[3,4]]">>),
    [[[1]]] = json:decode(<<"[[[1]]]">>),

    ?ASSERT_MATCH(#{}, json:decode(<<"{}">>)),
    ?ASSERT_MATCH(#{<<"a">> => 1}, json:decode(<<"{\"a\": 1}">>)),
    ?ASSERT_MATCH(#{<<"a">> => 1, <<"b">> => 2}, json:decode(<<"{\"a\": 1, \"b\": 2}">>)),
    ?ASSERT_MATCH(#{<<"a">> => #{<<"b">> => 1}}, json:decode(<<"{\"a\": {\"b\": 1}}">>)),
    ?ASSERT_MATCH(#{<<"items">> => [1, 2, 3]}, json:decode(<<"{\"items\": [1, 2, 3]}">>)),
    ok.

test_decode_whitespace() ->
    42 = json:decode(<<"  42  ">>),
    42 = json:decode(<<"\t42\n">>),
    42 = json:decode(<<"\r\n42\r\n">>),
    [1, 2] = json:decode(<<"[ 1 , 2 ]">>),
    ?ASSERT_MATCH(#{<<"a">> => 1}, json:decode(<<"{ \"a\" : 1 }">>)),
    [1] = json:decode(<<" \t\r\n[ \t\r\n1 \t\r\n] \t\r\n">>),
    ok.

test_decode_errors() ->
    ?ASSERT_ERROR(json:decode(<<>>)),
    ?ASSERT_ERROR(json:decode(<<"  ">>)),
    ?ASSERT_ERROR(json:decode(<<"\"unterminated">>)),
    ?ASSERT_ERROR(json:decode(<<"[1,">>)),
    ?ASSERT_ERROR(json:decode(<<"{\"a\"">>)),
    ?ASSERT_ERROR(json:decode(<<"{\"a\":">>)),
    ?ASSERT_ERROR(json:decode(<<"[">>)),
    ?ASSERT_ERROR(json:decode(<<"{">>)),

    ?ASSERT_ERROR(json:decode(<<"x">>)),
    ?ASSERT_ERROR(json:decode(<<",">>)),
    ?ASSERT_ERROR(json:decode(<<"42x">>)),
    ?ASSERT_ERROR(json:decode(<<"\"", 0, "\"">>)),
    ?ASSERT_ERROR(json:decode(<<"\"hello\nworld\"">>)),

    ?ASSERT_ERROR(json:decode(<<"\"\\uD800\"">>)),
    ?ASSERT_ERROR(json:decode(<<"\"\\uDC00\"">>)),
    ?ASSERT_ERROR(json:decode(<<"\"\\uD800\\u0041\"">>)),

    ?ASSERT_ERROR(json:decode(<<"-">>)),
    ?ASSERT_ERROR(json:decode(<<"1.">>)),
    ?ASSERT_ERROR(json:decode(<<"1e">>)),
    ?ASSERT_ERROR(json:decode(<<"1e+">>)),
    ok.

test_decode3() ->
    {42, my_acc, <<>>} = json:decode(<<"42">>, my_acc, #{}),
    {42, my_acc, <<"rest">>} = json:decode(<<"42rest">>, my_acc, #{}),

    {nil, ok, <<>>} = json:decode(<<"null">>, ok, #{null => nil}),

    StringFun = fun(Bin) -> binary_to_atom(Bin, utf8) end,
    {hello, ok, <<>>} = json:decode(<<"\"hello\"">>, ok, #{string => StringFun}),

    IntFun = fun(Bin) -> binary_to_integer(Bin) * 2 end,
    {84, ok, <<>>} = json:decode(<<"42">>, ok, #{integer => IntFun}),

    FloatFun = fun(Bin) -> round(binary_to_float(Bin)) end,
    {3, ok, <<>>} = json:decode(<<"3.14">>, ok, #{float => FloatFun}),

    ArrayDecoders = #{
        array_start => fun(_) -> {[], 0} end,
        array_push => fun(V, {Acc, Idx}) -> {[{Idx, V} | Acc], Idx + 1} end,
        array_finish => fun({Acc, _Idx}, OldAcc) -> {lists:reverse(Acc), OldAcc} end
    },
    {[{0, 1}, {1, 2}, {2, 3}], ok, <<>>} = json:decode(<<"[1,2,3]">>, ok, ArrayDecoders),

    ObjDecoders = #{
        object_start => fun(_) -> [] end,
        object_push => fun(K, V, Acc) -> [{K, V} | Acc] end,
        object_finish => fun(Acc, OldAcc) -> {lists:reverse(Acc), OldAcc} end
    },
    {[{<<"a">>, 1}, {<<"b">>, 2}], ok, <<>>} =
        json:decode(<<"{\"a\":1,\"b\":2}">>, ok, ObjDecoders),

    {42, ok, <<>>} = json:decode(<<"42 ">>, ok, #{}),
    {42, ok, <<" x">>} = json:decode(<<"42 x">>, ok, #{}),
    {true, ok, <<>>} = json:decode(<<"true  ">>, ok, #{}),
    {true, ok, <<"  x">>} = json:decode(<<"true  x">>, ok, #{}),
    ok.

test_decode_streaming() ->
    {true, ok, <<>>} = json:decode_start(<<"true">>, ok, #{}),

    {continue, S0} = json:decode_start(<<"42">>, ok, #{}),
    {42, ok, <<>>} = json:decode_continue(end_of_input, S0),

    {continue, S1} = json:decode_start(<<"[1,2">>, ok, #{}),
    {[1, 2, 3], ok, <<>>} = json:decode_continue(<<",3]">>, S1),

    {continue, S2} = json:decode_start(<<"\"hel">>, ok, #{}),
    {<<"hello">>, ok, <<>>} = json:decode_continue(<<"lo\"">>, S2),

    {continue, S3} = json:decode_start(<<"{">>, ok, #{}),
    {continue, S4} = json:decode_continue(<<"\"a\"">>, S3),
    {continue, S5} = json:decode_continue(<<":">>, S4),
    {continue, S6} = json:decode_continue(<<"1">>, S5),
    ?ASSERT_MATCH(#{<<"a">> => 1}, element(1, json:decode_continue(<<"}">>, S6))),

    {continue, S7} = json:decode_start(<<"[1,">>, ok, #{}),
    ?ASSERT_ERROR(json:decode_continue(end_of_input, S7)),

    {continue, S8} = json:decode_start(<<>>, ok, #{}),
    {continue, S9} = json:decode_continue(<<"42">>, S8),
    {42, ok, <<>>} = json:decode_continue(end_of_input, S9),

    {continue, S10} = json:decode_start(<<>>, ok, #{}),
    {42, ok, <<" x">>} = json:decode_continue(<<"42 x">>, S10),
    {continue, S11} = json:decode_start(<<>>, ok, #{}),
    {42, ok, <<>>} = json:decode_continue(<<"42 ">>, S11),

    ?ASSERT_ERROR(json:decode_start(<<"x">>, ok, #{})),
    ok.

test_decode_weather() ->
    Json =
        <<
            "{"
            "\"location\": {"
            "\"name\": \"\xe9\x82\xa3\xe9\xa0\x88\\u753A\","
            "\"country\": \"JP\","
            "\"coordinates\": [140.1209, 37.0198],"
            "\"utc_offset\": 9"
            "},"
            "\"current\": {"
            "\"temperature\": 18.5,"
            "\"humidity\": 62,"
            "\"conditions\": [\"partly_cloudy\", \"windy\"],"
            "\"wind\": {\"speed\": 5.2, \"direction\": \"NNW\"},"
            "\"precipitation\": false"
            "},"
            "\"forecast\": ["
            "{\"day\": 1, \"high\": 22.0, \"low\": 12.5, \"rain_probability\": 0.15},"
            "{\"day\": 2, \"high\": 19.0, \"low\": 10.0, \"rain_probability\": 0.80}"
            "],"
            "\"alerts\": null"
            "}"
        >>,
    Result = json:decode(Json),

    Location = maps:get(<<"location">>, Result),
    <<16#E9, 16#82, 16#A3, 16#E9, 16#A0, 16#88, 16#E7, 16#94, 16#BA>> = maps:get(
        <<"name">>, Location
    ),
    <<"JP">> = maps:get(<<"country">>, Location),
    [140.1209, 37.0198] = maps:get(<<"coordinates">>, Location),
    9 = maps:get(<<"utc_offset">>, Location),

    Current = maps:get(<<"current">>, Result),
    ?ASSERT_EQUALS(18.5, maps:get(<<"temperature">>, Current)),
    62 = maps:get(<<"humidity">>, Current),
    [<<"partly_cloudy">>, <<"windy">>] = maps:get(<<"conditions">>, Current),
    ?ASSERT_MATCH(
        #{<<"speed">> => 5.2, <<"direction">> => <<"NNW">>},
        maps:get(<<"wind">>, Current)
    ),
    false = maps:get(<<"precipitation">>, Current),

    [Day1, Day2] = maps:get(<<"forecast">>, Result),
    1 = maps:get(<<"day">>, Day1),
    ?ASSERT_EQUALS(22.0, maps:get(<<"high">>, Day1)),
    ?ASSERT_EQUALS(0.80, maps:get(<<"rain_probability">>, Day2)),

    null = maps:get(<<"alerts">>, Result),
    ok.

test_decode_edge_cases() ->
    0 = json:decode(<<"0">>),
    ?ASSERT_EQUALS(0.5, json:decode(<<"0.5">>)),
    ?ASSERT_ERROR(json:decode(<<"01">>)),
    {0, ok, <<"1">>} = json:decode(<<"01">>, ok, #{}),

    9007199254740993 = json:decode(<<"9007199254740993">>),

    ?ASSERT_EQUALS(1.0, json:decode(<<"1.0e0">>)),
    ?ASSERT_EQUALS(1.0, json:decode(<<"1.0e+0">>)),
    ?ASSERT_EQUALS(1.0, json:decode(<<"1.0e-0">>)),
    ok.

test_encode_basic() ->
    <<"0">> = to_bin(json:encode(0)),
    <<"42">> = to_bin(json:encode(42)),
    <<"-1">> = to_bin(json:encode(-1)),
    <<"9007199254740993">> = to_bin(json:encode(9007199254740993)),

    <<"1.0">> = to_bin(json:encode(1.0)),
    <<"3.14">> = to_bin(json:encode(3.14)),
    <<"-2.5">> = to_bin(json:encode(-2.5)),
    <<"-0.0">> = to_bin(json:encode(-0.0)),

    <<"true">> = to_bin(json:encode(true)),
    <<"false">> = to_bin(json:encode(false)),
    <<"null">> = to_bin(json:encode(null)),

    <<"\"hello\"">> = to_bin(json:encode(hello)),
    ok.

test_encode_strings() ->
    <<"\"\"">> = to_bin(json:encode(<<>>)),
    <<"\"hello\"">> = to_bin(json:encode(<<"hello">>)),
    <<"\"hello world\"">> = to_bin(json:encode(<<"hello world">>)),

    <<"\"\\\\\"">> = to_bin(json:encode(<<"\\">>)),
    <<"\"\\\"\"">> = to_bin(json:encode(<<"\"">>)),
    <<"\"\\n\"">> = to_bin(json:encode(<<"\n">>)),
    <<"\"\\r\"">> = to_bin(json:encode(<<"\r">>)),
    <<"\"\\t\"">> = to_bin(json:encode(<<"\t">>)),
    <<"\"\\b\"">> = to_bin(json:encode(<<"\b">>)),
    <<"\"\\f\"">> = to_bin(json:encode(<<"\f">>)),
    <<"\"\\u0001\"">> = to_bin(json:encode(<<1>>)),

    <<"\"hello\\nworld\"">> = to_bin(json:encode(<<"hello\nworld">>)),

    Bin = <<16#C3, 16#A9>>,
    <<"\"", 16#C3, 16#A9, "\"">> = to_bin(json:encode(Bin)),

    <<"\"hello\"">> = to_bin(json:encode_binary_escape_all(<<"hello">>)),
    <<"\"\\u00E9\"">> = to_bin(json:encode_binary_escape_all(<<16#C3, 16#A9>>)),
    <<"\"\\uD83D\\uDE00\"">> = to_bin(
        json:encode_binary_escape_all(<<16#F0, 16#9F, 16#98, 16#80>>)
    ),

    ?ASSERT_ERROR(json:encode(<<16#FF>>)),
    ?ASSERT_ERROR(json:encode(<<16#80>>)),
    ok.

test_encode_arrays() ->
    <<"[]">> = to_bin(json:encode([])),
    <<"[1]">> = to_bin(json:encode([1])),
    <<"[1,2,3]">> = to_bin(json:encode([1, 2, 3])),
    <<"[1,\"two\",true,null]">> = to_bin(json:encode([1, <<"two">>, true, null])),
    <<"[[1,2],[3,4]]">> = to_bin(json:encode([[1, 2], [3, 4]])),

    ?ASSERT_EQUALS(
        <<"{\"hello\":[119,111,114,108,100]}">>,
        to_bin(json:encode(#{hello => "world"}))
    ),
    ok.

test_encode_objects() ->
    <<"{}">> = to_bin(json:encode(#{})),

    ?ASSERT_MATCH(
        #{<<"a">> => 1, <<"b">> => 2},
        json:decode(to_bin(json:encode(#{<<"a">> => 1, <<"b">> => 2})))
    ),

    AtomResult = json:decode(to_bin(json:encode(#{foo => 1, bar => 2}))),
    1 = maps:get(<<"foo">>, AtomResult),
    2 = maps:get(<<"bar">>, AtomResult),

    ?ASSERT_EQUALS(
        to_bin(json:encode(#{<<"hello">> => <<"world">>})),
        to_bin(json:encode(#{hello => <<"world">>}))
    ),

    IntResult = json:decode(to_bin(json:encode(#{1 => <<"one">>, 2 => <<"two">>}))),
    <<"one">> = maps:get(<<"1">>, IntResult),
    <<"two">> = maps:get(<<"2">>, IntResult),

    Nested = #{<<"a">> => #{<<"b">> => 1}},
    ?ASSERT_MATCH(Nested, json:decode(to_bin(json:encode(Nested)))),
    ok.

test_encode_key_value_list() ->
    ?ASSERT_EQUALS(
        <<"{\"a\":1,\"b\":2}">>,
        to_bin(json:encode_key_value_list([{<<"a">>, 1}, {<<"b">>, 2}], fun json:encode_value/2))
    ),
    ok.

test_encode_checked() ->
    ?ASSERT_ERROR(
        json:encode_key_value_list_checked(
            [{<<"a">>, 1}, {<<"a">>, 2}], fun json:encode_value/2
        )
    ),

    ?ASSERT_ERROR(
        json:encode_map_checked(#{foo => 1, <<"foo">> => 2}, fun json:encode_value/2)
    ),
    ok.

test_encode_errors() ->
    ?ASSERT_ERROR(json:encode({a, tuple})),
    ?ASSERT_ERROR(json:encode([{hello, <<"world">>}])),
    ?ASSERT_ERROR(json:encode(#{"hello" => <<"world">>})),
    ok.

test_roundtrip() ->
    Terms = [
        42,
        -1,
        0,
        3.14,
        -0.0,
        true,
        false,
        null,
        <<"hello">>,
        <<>>,
        [],
        [1, 2, 3],
        #{},
        #{<<"key">> => <<"value">>},
        [#{<<"a">> => [1, true, null]}]
    ],
    lists:foreach(
        fun(Term) ->
            ?ASSERT_EQUALS(Term, json:decode(to_bin(json:encode(Term))))
        end,
        Terms
    ),
    ok.

test_streaming_splits() ->
    {continue, S5} = json:decode_start(<<"tr">>, ok, #{}),
    {true, ok, <<>>} = json:decode_continue(<<"ue">>, S5),

    {continue, S6} = json:decode_start(<<"nu">>, ok, #{}),
    {null, ok, <<>>} = json:decode_continue(<<"ll">>, S6),

    {continue, S7} = json:decode_start(<<"\"hel">>, ok, #{}),
    {<<"hello">>, ok, <<>>} = json:decode_continue(<<"lo\"">>, S7),

    {continue, S8} = json:decode_start(<<"\"\\u00">>, ok, #{}),
    {<<"A">>, ok, <<>>} = json:decode_continue(<<"41\"">>, S8),

    {continue, S9} = json:decode_start(<<"[1,">>, ok, #{}),
    {[1, 2], ok, <<>>} = json:decode_continue(<<"2]">>, S9),

    {continue, S10} = json:decode_start(<<"-">>, ok, #{}),
    {-42, ok, <<>>} = json:decode_continue(<<"42 ">>, S10),

    {continue, S3} = json:decode_start(<<"3.">>, ok, #{}),
    {3.14, ok, <<>>} = json:decode_continue(<<"14 ">>, S3),

    {continue, S4} = json:decode_start(<<"1e">>, ok, #{}),
    {1.0e5, ok, <<>>} = json:decode_continue(<<"5 ">>, S4),

    {continue, S11} = json:decode_start(<<"1.5e">>, ok, #{}),
    {1.5e3, ok, <<>>} = json:decode_continue(<<"3 ">>, S11),
    ok.

test_streaming_end_of_input() ->
    {continue, S1} = json:decode_start(<<"[1,">>, ok, #{}),
    ok =
        try json:decode_continue(end_of_input, S1) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,

    {continue, S2} = json:decode_start(<<>>, ok, #{}),
    ok =
        try json:decode_continue(end_of_input, S2) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,

    {continue, S3} = json:decode_start(<<"\"abc">>, ok, #{}),
    ok =
        try json:decode_continue(end_of_input, S3) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,

    {continue, S4} = json:decode_start(<<"tru">>, ok, #{}),
    ok =
        try json:decode_continue(end_of_input, S4) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    ok.

test_streaming_number_boundary() ->
    {continue, S1} = json:decode_start(<<"42">>, ok, #{}),
    {continue, S2} = json:decode_continue(<<"3">>, S1),
    {423, ok, <<>>} = json:decode_continue(end_of_input, S2),

    {continue, S3} = json:decode_start(<<"1">>, ok, #{}),
    {12, ok, <<>>} = json:decode_continue(<<"2 ">>, S3),

    {continue, S4} = json:decode_start(<<"0">>, ok, #{}),
    {0, ok, <<>>} = json:decode_continue(end_of_input, S4),

    {continue, S5} = json:decode_start(<<"3.14">>, ok, #{}),
    {3.14, ok, <<>>} = json:decode_continue(end_of_input, S5),

    {continue, S6} = json:decode_start(<<"1e5">>, ok, #{}),
    {1.0e5, ok, <<>>} = json:decode_continue(end_of_input, S6),

    {continue, S7} = json:decode_start(<<"-42">>, ok, #{}),
    {-42, ok, <<>>} = json:decode_continue(end_of_input, S7),

    42 = json:decode(<<"42">>),
    0 = json:decode(<<"0">>),
    3.14 = json:decode(<<"3.14">>),
    1.0e5 = json:decode(<<"1e5">>),
    -1 = json:decode(<<"-1">>),
    ok.

test_hex_error_classification() ->
    ok =
        try json:decode(<<"\"\\uGGGG\"">>) of
            _ -> error(should_have_failed)
        catch
            error:{unexpected_sequence, _} -> ok;
            error:{invalid_byte, _} -> error(wrong_error_tag)
        end,

    ok =
        try json:decode(<<"\"\\uD83D\\uZZZZ\"">>) of
            _ -> error(should_have_failed)
        catch
            error:{unexpected_sequence, _} -> ok;
            error:{invalid_byte, _} -> error(wrong_error_tag)
        end,
    ok.

test_encode_custom_key_encoder() ->
    Enc = fun
        (B, _E) when is_binary(B) -> json:encode_binary_escape_all(B);
        (Other, E) -> json:encode_value(Other, E)
    end,
    Result = iolist_to_binary(json:encode_map(#{<<16#C3, 16#A9>> => <<"v">>}, Enc)),
    Expected = <<"{\"\\u00E9\":\"v\"}">>,
    ?ASSERT_EQUALS(Expected, Result),
    ok.

test_encode_checked_custom_key_encoder() ->
    Enc = fun
        (B, _E) when is_binary(B) -> json:encode_binary_escape_all(B);
        (Other, E) -> json:encode_value(Other, E)
    end,
    Result = iolist_to_binary(
        json:encode_map_checked(#{<<16#C3, 16#A9>> => <<"v">>}, Enc)
    ),
    Expected = <<"{\"\\u00E9\":\"v\"}">>,
    ?ASSERT_EQUALS(Expected, Result),
    ok.

test_streaming_sliding_split() ->
    Jsons = sliding_split_jsons(),
    lists:foreach(fun run_sliding_split/1, Jsons),
    ok.

run_sliding_split(Json) ->
    Expected = json:decode(Json),
    Size = byte_size(Json),
    lists:foreach(
        fun(Pos) ->
            Left = binary_part(Json, 0, Pos),
            Right = binary_part(Json, Pos, Size - Pos),
            Result = streaming_decode(Left, Right),
            case Result of
                Expected ->
                    ok;
                Other ->
                    error(
                        {sliding_split_mismatch, [
                            {json, Json},
                            {split_at, Pos},
                            {expected, Expected},
                            {got, Other}
                        ]}
                    )
            end
        end,
        lists:seq(0, Size)
    ).

streaming_decode(Left, Right) ->
    case json:decode_start(Left, ok, #{}) of
        {Value, ok, Rest} ->
            %% Value complete in first chunk — remaining must be whitespace only
            case skip_ws(<<Rest/binary, Right/binary>>) of
                <<>> -> Value;
                _ -> error({unexpected_trailing, Left, Right, Value, Rest})
            end;
        {continue, State} ->
            streaming_continue(Right, State)
    end.

streaming_continue(<<>>, State) ->
    {Value, ok, <<>>} = json:decode_continue(end_of_input, State),
    Value;
streaming_continue(Data, State) ->
    case json:decode_continue(Data, State) of
        {Value, ok, _Rest} ->
            Value;
        {continue, State2} ->
            {Value, ok, <<>>} =
                json:decode_continue(end_of_input, State2),
            Value
    end.

skip_ws(<<$\s, R/binary>>) -> skip_ws(R);
skip_ws(<<$\t, R/binary>>) -> skip_ws(R);
skip_ws(<<$\n, R/binary>>) -> skip_ws(R);
skip_ws(<<$\r, R/binary>>) -> skip_ws(R);
skip_ws(Bin) -> Bin.

test_streaming_byte_by_byte() ->
    lists:foreach(fun run_byte_by_byte/1, sliding_split_jsons()),
    ok.

run_byte_by_byte(Json) ->
    Expected = json:decode(Json),
    <<First, Rest/binary>> = Json,
    {continue, State} = json:decode_start(<<First>>, ok, #{}),
    Result = feed_bytes(Rest, State),
    case Result of
        Expected -> ok;
        Other -> error({byte_by_byte_mismatch, [{json, Json}, {expected, Expected}, {got, Other}]})
    end.

feed_bytes(<<>>, State) ->
    {Value, ok, <<>>} = json:decode_continue(end_of_input, State),
    Value;
feed_bytes(<<B, Rest/binary>>, State) ->
    case json:decode_continue(<<B>>, State) of
        {Value, ok, _} when Rest =:= <<>> -> Value;
        {continue, State2} -> feed_bytes(Rest, State2)
    end.

sliding_split_jsons() ->
    [
        %% Mixed types with null
        <<"{\"temp\":18.5,\"wind\":null,\"rain\":false}">>,
        %% Array of mixed types
        <<"[1,-42,3.14,true,false,null,\"hello\"]">>,
        %% Nested objects
        <<"{\"a\":{\"b\":{\"c\":[1,2,3]}}}">>,
        %% Unicode escapes
        <<
            "{\"key\":\"caf\\u00E9\","
            "\"emoji\":\"\\uD83D\\uDE00\"}"
        >>,
        %% Kanji via unicode escapes
        <<
            "{\"name\":\"\\u90A3\\u9808\\u753A\","
            "\"country\":\"JP\"}"
        >>,
        %% Array of objects
        <<
            "[{\"id\":1,\"v\":true},"
            "{\"id\":2,\"v\":false}]"
        >>,
        %% Floats and exponents
        <<"{\"data\":[1.0e5,-0.0,1.5e-3],\"ok\":true}">>,
        %% String escapes
        <<
            "{\"path\":\"C:\\\\dir\\\\file\","
            "\"msg\":\"say \\\"hi\\\"\\n\"}"
        >>,
        %% Large integer + empty containers
        <<
            "{\"big\":9007199254740993,"
            "\"a\":[],\"o\":{}}"
        >>,
        %% Complex nested
        <<
            "[{\"k\":[null,[true,{\"x\":-1}]],"
            "\"y\":\"z\"}]"
        >>,
        %% Long UTF-8 (U+FBFD, 3-byte)
        <<
            "{\"longutf8\":\"\xEF\xAF\xB9\","
            "\"codepoint\":64505}"
        >>,
        %% Repeated long UTF-8
        <<
            "{\"longutf8repeated\":"
            "\"\xEF\xAF\xB9\xEF\xAF\xB9\xEF\xAF\xB9"
            "\xEF\xAF\xB9\xEF\xAF\xB9\","
            "\"is_repeated\":true}"
        >>,

        <<"42">>,
        <<"-1">>,
        <<"0">>,
        <<"3.14">>,
        <<"-0.5">>,
        <<"1e5">>,
        <<"1.5e-3">>,
        <<"-2.5e10">>,
        <<"true">>,
        <<"false">>,
        <<"null">>,
        <<"\"hello\"">>,
        <<"\"\"">>,
        <<"\"caf\\u00E9\"">>,
        <<"\"\\uD83D\\uDE00\"">>,
        <<"\"", 230, 188, 162, 229, 173, 151, "\"">>,
        <<"\"\\uD83D\\uDE00", 231, 181, 181, 230, 150, 135, 229, 173, 151, "\"">>,
        <<"\"nottrue\"">>,
        <<"\"notfalse\"">>,
        <<"\"notnull\"">>,
        <<"\"not42\"">>,
        <<"\"true-as-suffix\"">>,
        <<"\"false-as-suffix\"">>,
        <<"\"null-as-suffix\"">>,
        <<"\"true\"">>,
        <<"\"false\"">>,
        <<"\"null\"">>,

        <<
            "{\"location\":{\"name\":\"\\u90A3\\u9808\\u753A\","
            "\"country\":\"JP\","
            "\"coordinates\":[140.1209,37.0198],"
            "\"utc_offset\":9},"
            "\"current\":{\"temperature\":18.5,"
            "\"humidity\":62,"
            "\"conditions\":[\"partly_cloudy\",\"windy\"],"
            "\"wind\":{\"speed\":5.2,\"direction\":\"NNW\"},"
            "\"precipitation\":false},"
            "\"forecast\":["
            "{\"day\":1,\"high\":22.0,\"low\":12.5,"
            "\"rain_probability\":0.15},"
            "{\"day\":2,\"high\":19.0,\"low\":10.0,"
            "\"rain_probability\":0.80}],"
            "\"alerts\":null}"
        >>
    ].

test_deep_nesting() ->
    %% 1000 nested arrays: [[[...[1]...]]]
    N = 1000,
    Open = binary:copy(<<"[">>, N),
    Close = binary:copy(<<"]">>, N),
    Bin = <<Open/binary, "1", Close/binary>>,
    Expected = nest_value(1, N),
    Expected = json:decode(Bin),
    %% 1000 nested objects: {"k":{"k":...1...}}
    ObjOpen = iolist_to_binary(lists:duplicate(N, <<"{\"k\":">>)),
    ObjClose = binary:copy(<<"}">>, N),
    ObjBin = <<ObjOpen/binary, "1", ObjClose/binary>>,
    _ = json:decode(ObjBin),
    {continue, S1} = json:decode_start(Open, ok, #{}),
    {Expected, ok, <<>>} = json:decode_continue(<<"1", Close/binary>>, S1),
    ok =
        try json:decode(Open) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% Equivalent to the JSONTestSuite files that were excluded:
    %%   n_structure_100000_opening_arrays.json (100000 x "[")
    %%   n_structure_open_array_object.json (50000 x "[{"":")
    %% Full-size (100K) would pass but takes too long due to AtomVM GC pressure
    %% on the growing stack list. 10K proves the iterative decoder handles
    %% arbitrary depth without call-stack overflow.
    ok = expect_error(binary:copy(<<"[">>, 10000)),
    ok = expect_error(binary:copy(<<"[{\"\":">>, 5000)),
    ok.

expect_error(Bin) ->
    try json:decode(Bin) of
        _ -> error(should_have_failed)
    catch
        error:_ -> ok
    end.

nest_value(Value, 0) -> Value;
nest_value(Value, N) -> nest_value([Value], N - 1).

%%
%% JSONTestSuite data
%%

y_tests() ->
    [
        {"y_array_arraysWithSpaces.json", <<"W1tdICAgXQ==">>, [[]]},
        {"y_array_empty-string.json", <<"WyIiXQ==">>, [<<>>]},
        {"y_array_empty.json", <<"W10=">>, []},
        {"y_array_ending_with_newline.json", <<"WyJhIl0=">>, [<<97>>]},
        {"y_array_false.json", <<"W2ZhbHNlXQ==">>, [false]},
        {"y_array_heterogeneous.json", <<"W251bGwsIDEsICIxIiwge31d">>, [null, 1, <<49>>, #{}]},
        {"y_array_null.json", <<"W251bGxd">>, [null]},
        {"y_array_with_1_and_newline.json", <<"WzEKXQ==">>, [1]},
        {"y_array_with_leading_space.json", <<"IFsxXQ==">>, [1]},
        {"y_array_with_several_null.json", <<"WzEsbnVsbCxudWxsLG51bGwsMl0=">>, [
            1, null, null, null, 2
        ]},
        {"y_array_with_trailing_space.json", <<"WzJdIA==">>, [2]},
        {"y_number.json", <<"WzEyM2U2NV0=">>, [1.23e67]},
        {"y_number_0e+1.json", <<"WzBlKzFd">>, [0.0]},
        {"y_number_0e1.json", <<"WzBlMV0=">>, [0.0]},
        {"y_number_after_space.json", <<"WyA0XQ==">>, [4]},
        {"y_number_double_close_to_zero.json",
            <<"Wy0wLjAwMDAwMDAwMDAwMDAwMDAwMDAw", "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw",
                "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw", "MDAwMDAwMDAwMV0K">>,
            [-1.0e-78]},
        {"y_number_int_with_exp.json", <<"WzIwZTFd">>, [200.0]},
        {"y_number_minus_zero.json", <<"Wy0wXQ==">>, [0]},
        {"y_number_negative_int.json", <<"Wy0xMjNd">>, [-123]},
        {"y_number_negative_one.json", <<"Wy0xXQ==">>, [-1]},
        {"y_number_negative_zero.json", <<"Wy0wXQ==">>, [0]},
        {"y_number_real_capital_e.json", <<"WzFFMjJd">>, [1.0e22]},
        {"y_number_real_capital_e_neg_exp.json", <<"WzFFLTJd">>, [0.01]},
        {"y_number_real_capital_e_pos_exp.json", <<"WzFFKzJd">>, [100.0]},
        {"y_number_real_exponent.json", <<"WzEyM2U0NV0=">>, [1.23e47]},
        {"y_number_real_fraction_exponent.json", <<"WzEyMy40NTZlNzhd">>, [1.23456e80]},
        {"y_number_real_neg_exp.json", <<"WzFlLTJd">>, [0.01]},
        {"y_number_real_pos_exponent.json", <<"WzFlKzJd">>, [100.0]},
        {"y_number_simple_int.json", <<"WzEyM10=">>, [123]},
        {"y_number_simple_real.json", <<"WzEyMy40NTY3ODld">>, [123.456789]},
        {"y_object.json", <<"eyJhc2QiOiJzZGYiLCAiZGZnIjoiZmdo", "In0=">>,
            {external_term, <<"g3QAAAACbQAAAANhc2RtAAAAA3NkZm0A", "AAADZGZnbQAAAANmZ2g=">>}},
        {"y_object_basic.json", <<"eyJhc2QiOiJzZGYifQ==">>, #{
            <<97, 115, 100>> => <<115, 100, 102>>
        }},
        {"y_object_duplicated_key.json", <<"eyJhIjoiYiIsImEiOiJjIn0=">>, #{<<97>> => <<98>>}},
        {"y_object_duplicated_key_and_value.json", <<"eyJhIjoiYiIsImEiOiJiIn0=">>, #{
            <<97>> => <<98>>
        }},
        {"y_object_empty.json", <<"e30=">>, #{}},
        {"y_object_empty_key.json", <<"eyIiOjB9">>, #{<<>> => 0}},
        {"y_object_escaped_null_in_key.json", <<"eyJmb29cdTAwMDBiYXIiOiA0Mn0=">>, #{
            <<102, 111, 111, 0, 98, 97, 114>> => 42
        }},
        {"y_object_extreme_numbers.json",
            <<"eyAibWluIjogLTEuMGUrMjgsICJtYXgi", "OiAxLjBlKzI4IH0=">>, #{
                <<109, 97, 120>> => 1.0e28, <<109, 105, 110>> => -1.0e28
            }},
        {"y_object_long_strings.json",
            <<"eyJ4IjpbeyJpZCI6ICJ4eHh4eHh4eHh4", "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4",
                "eHh4eHh4In1dLCAiaWQiOiAieHh4eHh4", "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4",
                "eHh4eHh4eHh4eCJ9">>,
            {external_term,
                <<"g3QAAAACbQAAAAJpZG0AAAAoeHh4eHh4", "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4",
                    "eHh4eHh4eHh4eG0AAAABeGwAAAABdAAA", "AAFtAAAAAmlkbQAAACh4eHh4eHh4eHh4",
                    "eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4", "eHh4eHh4ag==">>}},
        {"y_object_simple.json", <<"eyJhIjpbXX0=">>, #{<<97>> => []}},
        {"y_object_string_unicode.json",
            <<"eyJ0aXRsZSI6Ilx1MDQxZlx1MDQzZVx1", "MDQzYlx1MDQ0Mlx1MDQzZVx1MDQ0MFx1",
                "MDQzMCBcdTA0MTdcdTA0MzVcdTA0M2Nc", "dTA0M2JcdTA0MzVcdTA0M2FcdTA0M2Vc",
                "dTA0M2ZcdTA0MzAiIH0=">>,
            {external_term,
                <<"g3QAAAABbQAAAAV0aXRsZW0AAAAh0J/Q", "vtC70YLQvtGA0LAg0JfQtdC80LvQtdC6",
                    "0L7Qv9Cw">>}},
        {"y_object_with_newlines.json", <<"ewoiYSI6ICJiIgp9">>, #{<<97>> => <<98>>}},
        {"y_string_1_2_3_bytes_UTF-8_sequences.json", <<"WyJcdTAwNjBcdTAxMmFcdTEyQUIiXQ==">>, [
            <<96, 196, 170, 225, 138, 171>>
        ]},
        {"y_string_accepted_surrogate_pair.json", <<"WyJcdUQ4MDFcdWRjMzciXQ==">>, [
            <<240, 144, 144, 183>>
        ]},
        {"y_string_accepted_surrogate_pairs.json",
            <<"WyJcdWQ4M2RcdWRlMzlcdWQ4M2RcdWRj", "OGQiXQ==">>, [
                <<240, 159, 152, 185, 240, 159, 146, 141>>
            ]},
        {"y_string_allowed_escapes.json", <<"WyJcIlxcXC9cYlxmXG5cclx0Il0=">>, [
            <<34, 92, 47, 8, 12, 10, 13, 9>>
        ]},
        {"y_string_backslash_and_u_escaped_zero.json", <<"WyJcXHUwMDAwIl0=">>, [
            <<92, 117, 48, 48, 48, 48>>
        ]},
        {"y_string_backslash_doublequotes.json", <<"WyJcIiJd">>, [<<34>>]},
        {"y_string_comments.json", <<"WyJhLypiKi9jLypkLy9lIl0=">>, [
            <<97, 47, 42, 98, 42, 47, 99, 47, 42, 100, 47, 47, 101>>
        ]},
        {"y_string_double_escape_a.json", <<"WyJcXGEiXQ==">>, [<<92, 97>>]},
        {"y_string_double_escape_n.json", <<"WyJcXG4iXQ==">>, [<<92, 110>>]},
        {"y_string_escaped_control_character.json", <<"WyJcdTAwMTIiXQ==">>, [<<18>>]},
        {"y_string_escaped_noncharacter.json", <<"WyJcdUZGRkYiXQ==">>, [<<239, 191, 191>>]},
        {"y_string_in_array.json", <<"WyJhc2QiXQ==">>, [<<97, 115, 100>>]},
        {"y_string_in_array_with_leading_space.json", <<"WyAiYXNkIl0=">>, [<<97, 115, 100>>]},
        {"y_string_last_surrogates_1_and_2.json", <<"WyJcdURCRkZcdURGRkYiXQ==">>, [
            <<244, 143, 191, 191>>
        ]},
        {"y_string_nbsp_uescaped.json", <<"WyJuZXdcdTAwQTBsaW5lIl0=">>, [
            <<110, 101, 119, 194, 160, 108, 105, 110, 101>>
        ]},
        {"y_string_nonCharacterInUTF-8_U+10FFFF.json", <<"WyL0j7+/Il0=">>, [<<244, 143, 191, 191>>]},
        {"y_string_nonCharacterInUTF-8_U+FFFF.json", <<"WyLvv78iXQ==">>, [<<239, 191, 191>>]},
        {"y_string_null_escape.json", <<"WyJcdTAwMDAiXQ==">>, [<<0>>]},
        {"y_string_one-byte-utf-8.json", <<"WyJcdTAwMmMiXQ==">>, [<<44>>]},
        {"y_string_pi.json", <<"WyLPgCJd">>, [<<207, 128>>]},
        {"y_string_reservedCharacterInUTF-8_U+1BFFF.json", <<"WyLwm7+/Il0=">>, [
            <<240, 155, 191, 191>>
        ]},
        {"y_string_simple_ascii.json", <<"WyJhc2QgIl0=">>, [<<97, 115, 100, 32>>]},
        {"y_string_space.json", <<"IiAi">>, <<32>>},
        {"y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF.json", <<"WyJcdUQ4MzRcdURkMWUiXQ==">>, [
                <<240, 157, 132, 158>>
            ]},
        {"y_string_three-byte-utf-8.json", <<"WyJcdTA4MjEiXQ==">>, [<<224, 160, 161>>]},
        {"y_string_two-byte-utf-8.json", <<"WyJcdTAxMjMiXQ==">>, [<<196, 163>>]},
        {"y_string_u+2028_line_sep.json", <<"WyLigKgiXQ==">>, [<<226, 128, 168>>]},
        {"y_string_u+2029_par_sep.json", <<"WyLigKkiXQ==">>, [<<226, 128, 169>>]},
        {"y_string_uEscape.json", <<"WyJcdTAwNjFcdTMwYWZcdTMwRUFcdTMw", "YjkiXQ==">>, [
            <<97, 227, 130, 175, 227, 131, 170, 227, 130, 185>>
        ]},
        {"y_string_uescaped_newline.json", <<"WyJuZXdcdTAwMEFsaW5lIl0=">>, [
            <<110, 101, 119, 10, 108, 105, 110, 101>>
        ]},
        {"y_string_unescaped_char_delete.json", <<"WyJ/Il0=">>, [<<127>>]},
        {"y_string_unicode.json", <<"WyJcdUE2NkQiXQ==">>, [<<234, 153, 173>>]},
        {"y_string_unicodeEscapedBackslash.json", <<"WyJcdTAwNUMiXQ==">>, [<<92>>]},
        {"y_string_unicode_2.json", <<"WyLijYLjiLTijYIiXQ==">>, [
            <<226, 141, 130, 227, 136, 180, 226, 141, 130>>
        ]},
        {"y_string_unicode_U+10FFFE_nonchar.json", <<"WyJcdURCRkZcdURGRkUiXQ==">>, [
            <<244, 143, 191, 190>>
        ]},
        {"y_string_unicode_U+1FFFE_nonchar.json", <<"WyJcdUQ4M0ZcdURGRkUiXQ==">>, [
            <<240, 159, 191, 190>>
        ]},
        {"y_string_unicode_U+200B_ZERO_WIDTH_SPACE.json", <<"WyJcdTIwMEIiXQ==">>, [
            <<226, 128, 139>>
        ]},
        {"y_string_unicode_U+2064_invisible_plus.json", <<"WyJcdTIwNjQiXQ==">>, [<<226, 129, 164>>]},
        {"y_string_unicode_U+FDD0_nonchar.json", <<"WyJcdUZERDAiXQ==">>, [<<239, 183, 144>>]},
        {"y_string_unicode_U+FFFE_nonchar.json", <<"WyJcdUZGRkUiXQ==">>, [<<239, 191, 190>>]},
        {"y_string_unicode_escaped_double_quote.json", <<"WyJcdTAwMjIiXQ==">>, [<<34>>]},
        {"y_string_utf8.json", <<"WyLigqzwnYSeIl0=">>, [<<226, 130, 172, 240, 157, 132, 158>>]},
        {"y_string_with_del_character.json", <<"WyJhf2EiXQ==">>, [<<97, 127, 97>>]},
        {"y_structure_lonely_false.json", <<"ZmFsc2U=">>, false},
        {"y_structure_lonely_int.json", <<"NDI=">>, 42},
        {"y_structure_lonely_negative_real.json", <<"LTAuMQ==">>, -0.1},
        {"y_structure_lonely_null.json", <<"bnVsbA==">>, null},
        {"y_structure_lonely_string.json", <<"ImFzZCI=">>, <<97, 115, 100>>},
        {"y_structure_lonely_true.json", <<"dHJ1ZQ==">>, true},
        {"y_structure_string_empty.json", <<"IiI=">>, <<>>},
        {"y_structure_trailing_newline.json", <<"WyJhIl0K">>, [<<97>>]},
        {"y_structure_true_in_array.json", <<"W3RydWVd">>, [true]},
        {"y_structure_whitespace_array.json", <<"IFtdIA==">>, []}
    ].

n_tests() ->
    [
        {"n_array_1_true_without_comma.json", <<"WzEgdHJ1ZV0=">>, {invalid_byte, 116}},
        {"n_array_a_invalid_utf8.json", <<"W2HlXQ==">>, {invalid_byte, 97}},
        {"n_array_colon_instead_of_comma.json", <<"WyIiOiAxXQ==">>, {invalid_byte, 58}},
        {"n_array_comma_after_close.json", <<"WyIiXSw=">>, {invalid_byte, 44}},
        {"n_array_comma_and_number.json", <<"WywxXQ==">>, {invalid_byte, 44}},
        {"n_array_double_comma.json", <<"WzEsLDJd">>, {invalid_byte, 44}},
        {"n_array_double_extra_comma.json", <<"WyJ4IiwsXQ==">>, {invalid_byte, 44}},
        {"n_array_extra_close.json", <<"WyJ4Il1d">>, {invalid_byte, 93}},
        {"n_array_extra_comma.json", <<"WyIiLF0=">>, {invalid_byte, 93}},
        {"n_array_incomplete.json", <<"WyJ4Ig==">>, unexpected_end},
        {"n_array_incomplete_invalid_value.json", <<"W3g=">>, {invalid_byte, 120}},
        {"n_array_inner_array_no_comma.json", <<"WzNbNF1d">>, {invalid_byte, 91}},
        {"n_array_invalid_utf8.json", <<"W/9d">>, {invalid_byte, 255}},
        {"n_array_items_separated_by_semicolon.json", <<"WzE6Ml0=">>, {invalid_byte, 58}},
        {"n_array_just_comma.json", <<"Wyxd">>, {invalid_byte, 44}},
        {"n_array_just_minus.json", <<"Wy1d">>, {invalid_byte, 93}},
        {"n_array_missing_value.json", <<"WyAgICwgIiJd">>, {invalid_byte, 44}},
        {"n_array_newlines_unclosed.json", <<"WyJhIiwKNAosMSw=">>, unexpected_end},
        {"n_array_number_and_comma.json", <<"WzEsXQ==">>, {invalid_byte, 93}},
        {"n_array_number_and_several_commas.json", <<"WzEsLF0=">>, {invalid_byte, 44}},
        {"n_array_spaces_vertical_tab_formfeed.json", <<"WyILYSJcZl0=">>, {invalid_byte, 11}},
        {"n_array_star_inside.json", <<"Wypd">>, {invalid_byte, 42}},
        {"n_array_unclosed.json", <<"WyIi">>, unexpected_end},
        {"n_array_unclosed_trailing_comma.json", <<"WzEs">>, unexpected_end},
        {"n_array_unclosed_with_new_lines.json", <<"WzEsCjEKLDE=">>, unexpected_end},
        {"n_array_unclosed_with_object_inside.json", <<"W3t9">>, unexpected_end},
        {"n_incomplete_false.json", <<"W2ZhbHNd">>, unexpected_end},
        {"n_incomplete_null.json", <<"W251bF0=">>, unexpected_end},
        {"n_incomplete_true.json", <<"W3RydV0=">>, unexpected_end},
        {"n_multidigit_number_then_00.json", <<"MTIzAA==">>, {invalid_byte, 0}},
        {"n_number_++.json", <<"WysrMTIzNF0=">>, {invalid_byte, 43}},
        {"n_number_+1.json", <<"WysxXQ==">>, {invalid_byte, 43}},
        {"n_number_+Inf.json", <<"WytJbmZd">>, {invalid_byte, 43}},
        {"n_number_-01.json", <<"Wy0wMV0=">>, {invalid_byte, 49}},
        {"n_number_-1.0..json", <<"Wy0xLjAuXQ==">>, {invalid_byte, 46}},
        {"n_number_-2..json", <<"Wy0yLl0=">>, {invalid_byte, 93}},
        {"n_number_-NaN.json", <<"Wy1OYU5d">>, {invalid_byte, 78}},
        {"n_number_.-1.json", <<"Wy4tMV0=">>, {invalid_byte, 46}},
        {"n_number_.2e-3.json", <<"Wy4yZS0zXQ==">>, {invalid_byte, 46}},
        {"n_number_0.1.2.json", <<"WzAuMS4yXQ==">>, {invalid_byte, 46}},
        {"n_number_0.3e+.json", <<"WzAuM2UrXQ==">>, {invalid_byte, 93}},
        {"n_number_0.3e.json", <<"WzAuM2Vd">>, {invalid_byte, 93}},
        {"n_number_0.e1.json", <<"WzAuZTFd">>, {invalid_byte, 101}},
        {"n_number_0_capital_E+.json", <<"WzBFK10=">>, {invalid_byte, 93}},
        {"n_number_0_capital_E.json", <<"WzBFXQ==">>, {invalid_byte, 93}},
        {"n_number_0e+.json", <<"WzBlK10=">>, {invalid_byte, 93}},
        {"n_number_0e.json", <<"WzBlXQ==">>, {invalid_byte, 93}},
        {"n_number_1.0e+.json", <<"WzEuMGUrXQ==">>, {invalid_byte, 93}},
        {"n_number_1.0e-.json", <<"WzEuMGUtXQ==">>, {invalid_byte, 93}},
        {"n_number_1.0e.json", <<"WzEuMGVd">>, {invalid_byte, 93}},
        {"n_number_1_000.json", <<"WzEgMDAwLjBd">>, {invalid_byte, 48}},
        {"n_number_1eE2.json", <<"WzFlRTJd">>, {invalid_byte, 69}},
        {"n_number_2.e+3.json", <<"WzIuZSszXQ==">>, {invalid_byte, 101}},
        {"n_number_2.e-3.json", <<"WzIuZS0zXQ==">>, {invalid_byte, 101}},
        {"n_number_2.e3.json", <<"WzIuZTNd">>, {invalid_byte, 101}},
        {"n_number_9.e+.json", <<"WzkuZStd">>, {invalid_byte, 101}},
        {"n_number_Inf.json", <<"W0luZl0=">>, {invalid_byte, 73}},
        {"n_number_NaN.json", <<"W05hTl0=">>, {invalid_byte, 78}},
        {"n_number_U+FF11_fullwidth_digit_one.json", <<"W++8kV0=">>, {invalid_byte, 239}},
        {"n_number_expression.json", <<"WzErMl0=">>, {invalid_byte, 43}},
        {"n_number_hex_1_digit.json", <<"WzB4MV0=">>, {invalid_byte, 120}},
        {"n_number_hex_2_digits.json", <<"WzB4NDJd">>, {invalid_byte, 120}},
        {"n_number_infinity.json", <<"W0luZmluaXR5XQ==">>, {invalid_byte, 73}},
        {"n_number_invalid+-.json", <<"WzBlKy0xXQ==">>, {invalid_byte, 45}},
        {"n_number_invalid-negative-real.json", <<"Wy0xMjMuMTIzZm9vXQ==">>, {invalid_byte, 102}},
        {"n_number_invalid-utf-8-in-bigger-int.json", <<"WzEyM+Vd">>, {invalid_byte, 229}},
        {"n_number_invalid-utf-8-in-exponent.json", <<"WzFlMeVd">>, {invalid_byte, 229}},
        {"n_number_invalid-utf-8-in-int.json", <<"WzDlXQo=">>, {invalid_byte, 229}},
        {"n_number_minus_infinity.json", <<"Wy1JbmZpbml0eV0=">>, {invalid_byte, 73}},
        {"n_number_minus_sign_with_trailing_garbage.json", <<"Wy1mb29d">>, {invalid_byte, 102}},
        {"n_number_minus_space_1.json", <<"Wy0gMV0=">>, {invalid_byte, 32}},
        {"n_number_neg_int_starting_with_zero.json", <<"Wy0wMTJd">>, {invalid_byte, 49}},
        {"n_number_neg_real_without_int_part.json", <<"Wy0uMTIzXQ==">>, {invalid_byte, 46}},
        {"n_number_neg_with_garbage_at_end.json", <<"Wy0xeF0=">>, {invalid_byte, 120}},
        {"n_number_real_garbage_after_e.json", <<"WzFlYV0=">>, {invalid_byte, 97}},
        {"n_number_real_with_invalid_utf8_after_e.json", <<"WzFl5V0=">>, {invalid_byte, 229}},
        {"n_number_real_without_fractional_part.json", <<"WzEuXQ==">>, {invalid_byte, 93}},
        {"n_number_starting_with_dot.json", <<"Wy4xMjNd">>, {invalid_byte, 46}},
        {"n_number_with_alpha.json", <<"WzEuMmEtM10=">>, {invalid_byte, 97}},
        {"n_number_with_alpha_char.json", <<"WzEuODAxMTY3MDAzMzM3NjUxNEgtMzA4", "XQ==">>,
            {invalid_byte, 72}},
        {"n_number_with_leading_zero.json", <<"WzAxMl0=">>, {invalid_byte, 49}},
        {"n_object_bad_value.json", <<"WyJ4IiwgdHJ1dGhd">>, {invalid_byte, 114}},
        {"n_object_bracket_key.json", <<"e1s6ICJ4In0K">>, {invalid_byte, 91}},
        {"n_object_comma_instead_of_colon.json", <<"eyJ4IiwgbnVsbH0=">>, {invalid_byte, 44}},
        {"n_object_double_colon.json", <<"eyJ4Ijo6ImIifQ==">>, {invalid_byte, 58}},
        {"n_object_emoji.json", <<"e/Cfh6jwn4etfQ==">>, {invalid_byte, 240}},
        {"n_object_garbage_at_end.json", <<"eyJhIjoiYSIgMTIzfQ==">>, {invalid_byte, 49}},
        {"n_object_key_with_single_quotes.json", <<"e2tleTogJ3ZhbHVlJ30=">>, {invalid_byte, 107}},
        {"n_object_lone_continuation_byte_in_key_and_trailing_comma.json", <<"eyK5IjoiMCIsfQ==">>,
            {invalid_byte, 185}},
        {"n_object_missing_colon.json", <<"eyJhIiBifQ==">>, {invalid_byte, 98}},
        {"n_object_missing_key.json", <<"ezoiYiJ9">>, {invalid_byte, 58}},
        {"n_object_missing_semicolon.json", <<"eyJhIiAiYiJ9">>, {invalid_byte, 34}},
        {"n_object_missing_value.json", <<"eyJhIjo=">>, unexpected_end},
        {"n_object_no-colon.json", <<"eyJhIg==">>, unexpected_end},
        {"n_object_non_string_key.json", <<"ezE6MX0=">>, {invalid_byte, 49}},
        {"n_object_non_string_key_but_huge_number_instead.json", <<"ezk5OTlFOTk5OToxfQ==">>,
            {invalid_byte, 57}},
        {"n_object_repeated_null_null.json", <<"e251bGw6bnVsbCxudWxsOm51bGx9">>,
            {invalid_byte, 110}},
        {"n_object_several_trailing_commas.json", <<"eyJpZCI6MCwsLCwsfQ==">>, {invalid_byte, 44}},
        {"n_object_single_quote.json", <<"eydhJzowfQ==">>, {invalid_byte, 39}},
        {"n_object_trailing_comma.json", <<"eyJpZCI6MCx9">>, {invalid_byte, 125}},
        {"n_object_trailing_comment.json", <<"eyJhIjoiYiJ9LyoqLw==">>, {invalid_byte, 47}},
        {"n_object_trailing_comment_open.json", <<"eyJhIjoiYiJ9LyoqLy8=">>, {invalid_byte, 47}},
        {"n_object_trailing_comment_slash_open.json", <<"eyJhIjoiYiJ9Ly8=">>, {invalid_byte, 47}},
        {"n_object_trailing_comment_slash_open_incomplete.json", <<"eyJhIjoiYiJ9Lw==">>,
            {invalid_byte, 47}},
        {"n_object_two_commas_in_a_row.json", <<"eyJhIjoiYiIsLCJjIjoiZCJ9">>, {invalid_byte, 44}},
        {"n_object_unquoted_key.json", <<"e2E6ICJiIn0=">>, {invalid_byte, 97}},
        {"n_object_unterminated-value.json", <<"eyJhIjoiYQ==">>, unexpected_end},
        {"n_object_with_single_string.json", <<"eyAiZm9vIiA6ICJiYXIiLCAiYSIgfQ==">>,
            {invalid_byte, 125}},
        {"n_object_with_trailing_garbage.json", <<"eyJhIjoiYiJ9Iw==">>, {invalid_byte, 35}},
        {"n_single_space.json", <<"IA==">>, unexpected_end},
        {"n_string_1_surrogate_then_escape.json", <<"WyJcdUQ4MDBcIl0=">>, unexpected_end},
        {"n_string_1_surrogate_then_escape_u.json", <<"WyJcdUQ4MDBcdSJd">>, unexpected_end},
        {"n_string_1_surrogate_then_escape_u1.json", <<"WyJcdUQ4MDBcdTEiXQ==">>, unexpected_end},
        {"n_string_1_surrogate_then_escape_u1x.json", <<"WyJcdUQ4MDBcdTF4Il0=">>,
            {external_term, <<"g2gCdxN1bmV4cGVjdGVkX3NlcXVlbmNl", "bQAAAAxcdUQ4MDBcdTF4Il0=">>}},
        {"n_string_accentuated_char_no_quotes.json", <<"W8OpXQ==">>, {invalid_byte, 195}},
        {"n_string_backslash_00.json", <<"WyJcACJd">>, {invalid_byte, 0}},
        {"n_string_escape_x.json", <<"WyJceDAwIl0=">>, {invalid_byte, 120}},
        {"n_string_escaped_backslash_bad.json", <<"WyJcXFwiXQ==">>, unexpected_end},
        {"n_string_escaped_ctrl_char_tab.json", <<"WyJcCSJd">>, {invalid_byte, 9}},
        {"n_string_escaped_emoji.json", <<"WyJc8J+MgCJd">>, {invalid_byte, 240}},
        {"n_string_incomplete_escape.json", <<"WyJcIl0=">>, unexpected_end},
        {"n_string_incomplete_escaped_character.json", <<"WyJcdTAwQSJd">>,
            {unexpected_sequence, <<92, 117, 48, 48, 65, 34>>}},
        {"n_string_incomplete_surrogate.json", <<"WyJcdUQ4MzRcdURkIl0=">>,
            {external_term, <<"g2gCdxN1bmV4cGVjdGVkX3NlcXVlbmNl", "bQAAAAxcdUQ4MzRcdURkIl0=">>}},
        {"n_string_incomplete_surrogate_escape_invalid.json", <<"WyJcdUQ4MDBcdUQ4MDBceCJd">>,
            {unexpected_sequence, <<92, 117, 68, 56, 48, 48, 92, 117, 68, 56, 48, 48>>}},
        {"n_string_invalid-utf-8-in-escape.json", <<"WyJcdeUiXQ==">>, unexpected_end},
        {"n_string_invalid_backslash_esc.json", <<"WyJcYSJd">>, {invalid_byte, 97}},
        {"n_string_invalid_unicode_escape.json", <<"WyJcdXFxcXEiXQ==">>,
            {unexpected_sequence, <<92, 117, 113, 113, 113, 113>>}},
        {"n_string_invalid_utf8_after_escape.json", <<"WyJc5SJd">>, {invalid_byte, 229}},
        {"n_string_leading_uescaped_thinspace.json", <<"W1x1MDAyMCJhc2QiXQ==">>,
            {invalid_byte, 92}},
        {"n_string_no_quotes_with_bad_escape.json", <<"W1xuXQ==">>, {invalid_byte, 92}},
        {"n_string_single_doublequote.json", <<"Ig==">>, unexpected_end},
        {"n_string_single_quote.json", <<"WydzaW5nbGUgcXVvdGUnXQ==">>, {invalid_byte, 39}},
        {"n_string_single_string_no_double_quotes.json", <<"YWJj">>, {invalid_byte, 97}},
        {"n_string_start_escape_unclosed.json", <<"WyJc">>, unexpected_end},
        {"n_string_unescaped_ctrl_char.json", <<"WyJhAGEiXQ==">>, {invalid_byte, 0}},
        {"n_string_unescaped_newline.json", <<"WyJuZXcKbGluZSJd">>, {invalid_byte, 10}},
        {"n_string_unescaped_tab.json", <<"WyIJIl0=">>, {invalid_byte, 9}},
        {"n_string_unicode_CapitalU.json", <<"IlxVQTY2RCI=">>, {invalid_byte, 85}},
        {"n_string_with_trailing_garbage.json", <<"IiJ4">>, {invalid_byte, 120}},
        {"n_structure_U+2060_word_joined.json", <<"W+KBoF0=">>, {invalid_byte, 226}},
        {"n_structure_UTF8_BOM_no_data.json", <<"77u/">>, {invalid_byte, 239}},
        {"n_structure_angle_bracket_..json", <<"PC4+">>, {invalid_byte, 60}},
        {"n_structure_angle_bracket_null.json", <<"WzxudWxsPl0=">>, {invalid_byte, 60}},
        {"n_structure_array_trailing_garbage.json", <<"WzFdeA==">>, {invalid_byte, 120}},
        {"n_structure_array_with_extra_array_close.json", <<"WzFdXQ==">>, {invalid_byte, 93}},
        {"n_structure_array_with_unclosed_string.json", <<"WyJhc2Rd">>, unexpected_end},
        {"n_structure_ascii-unicode-identifier.json", <<"YcOl">>, {invalid_byte, 97}},
        {"n_structure_capitalized_True.json", <<"W1RydWVd">>, {invalid_byte, 84}},
        {"n_structure_close_unopened_array.json", <<"MV0=">>, {invalid_byte, 93}},
        {"n_structure_comma_instead_of_closing_brace.json", <<"eyJ4IjogdHJ1ZSw=">>, unexpected_end},
        {"n_structure_double_array.json", <<"W11bXQ==">>, {invalid_byte, 91}},
        {"n_structure_end_array.json", <<"XQ==">>, {invalid_byte, 93}},
        {"n_structure_incomplete_UTF8_BOM.json", <<"77t7fQ==">>, {invalid_byte, 239}},
        {"n_structure_lone-invalid-utf-8.json", <<"5Q==">>, {invalid_byte, 229}},
        {"n_structure_lone-open-bracket.json", <<"Ww==">>, unexpected_end},
        {"n_structure_no_data.json", <<"">>, unexpected_end},
        {"n_structure_null-byte-outside-string.json", <<"WwBd">>, {invalid_byte, 0}},
        {"n_structure_number_with_trailing_garbage.json", <<"MkA=">>, {invalid_byte, 64}},
        {"n_structure_object_followed_by_closing_object.json", <<"e319">>, {invalid_byte, 125}},
        {"n_structure_object_unclosed_no_value.json", <<"eyIiOg==">>, unexpected_end},
        {"n_structure_object_with_comment.json", <<"eyJhIjovKmNvbW1lbnQqLyJiIn0=">>,
            {invalid_byte, 47}},
        {"n_structure_object_with_trailing_garbage.json", <<"eyJhIjogdHJ1ZX0gIngi">>,
            {invalid_byte, 32}},
        {"n_structure_open_array_apostrophe.json", <<"Wyc=">>, {invalid_byte, 39}},
        {"n_structure_open_array_comma.json", <<"Wyw=">>, {invalid_byte, 44}},
        {"n_structure_open_array_open_object.json", <<"W3s=">>, unexpected_end},
        {"n_structure_open_array_open_string.json", <<"WyJh">>, unexpected_end},
        {"n_structure_open_array_string.json", <<"WyJhIg==">>, unexpected_end},
        {"n_structure_open_object.json", <<"ew==">>, unexpected_end},
        {"n_structure_open_object_close_array.json", <<"e10=">>, {invalid_byte, 93}},
        {"n_structure_open_object_comma.json", <<"eyw=">>, {invalid_byte, 44}},
        {"n_structure_open_object_open_array.json", <<"e1s=">>, {invalid_byte, 91}},
        {"n_structure_open_object_open_string.json", <<"eyJh">>, unexpected_end},
        {"n_structure_open_object_string_with_apostrophes.json", <<"eydhJw==">>,
            {invalid_byte, 39}},
        {"n_structure_open_open.json", <<"WyJce1siXHtbIlx7WyJcew==">>, {invalid_byte, 123}},
        {"n_structure_single_eacute.json", <<"6Q==">>, {invalid_byte, 233}},
        {"n_structure_single_star.json", <<"Kg==">>, {invalid_byte, 42}},
        {"n_structure_trailing_#.json", <<"eyJhIjoiYiJ9I3t9">>, {invalid_byte, 35}},
        {"n_structure_uescaped_LF_before_string.json", <<"W1x1MDAwQSIiXQ==">>, {invalid_byte, 92}},
        {"n_structure_unclosed_array.json", <<"WzE=">>, unexpected_end},
        {"n_structure_unclosed_array_partial_null.json", <<"WyBmYWxzZSwgbnVs">>, unexpected_end},
        {"n_structure_unclosed_array_unfinished_false.json", <<"WyB0cnVlLCBmYWxz">>,
            unexpected_end},
        {"n_structure_unclosed_array_unfinished_true.json", <<"WyBmYWxzZSwgdHJ1">>, unexpected_end},
        {"n_structure_unclosed_object.json", <<"eyJhc2QiOiJhc2Qi">>, unexpected_end},
        {"n_structure_unicode-identifier.json", <<"w6U=">>, {invalid_byte, 195}},
        {"n_structure_whitespace_U+2060_word_joiner.json", <<"W+KBoF0=">>, {invalid_byte, 226}},
        {"n_structure_whitespace_formfeed.json", <<"Wwxd">>, {invalid_byte, 12}}
    ].

i_tests() ->
    [
        {"i_number_double_huge_neg_exp.json", <<"WzEyMy40NTZlLTc4OV0=">>, {ok, [0.0]}},
        {"i_number_huge_exp.json",
            <<"WzAuNGUwMDY2OTk5OTk5OTk5OTk5OTk5", "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5",
                "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5", "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5",
                "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5", "OTk5OTk2OTk5OTk5OTAwNl0=">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAIcwLjRlMDA2Njk5",
                    "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5", "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5",
                    "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5", "OTk5OTk5OTk5OTk5OTk5OTk5OTk5OTk5",
                    "OTk5OTk5OTk5OTk5OTk5OTk5Njk5OTk5", "OTkwMDY=">>}},
        {"i_number_neg_int_huge_exp.json", <<"Wy0xZSs5OTk5XQ==">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAAotMS4wZSs5OTk5">>}},
        {"i_number_pos_double_huge_exp.json", <<"WzEuNWUrOTk5OV0=">>,
            {error, {unexpected_sequence, <<49, 46, 53, 101, 43, 57, 57, 57, 57>>}}},
        {"i_number_real_neg_overflow.json", <<"Wy0xMjMxMjNlMTAwMDAwXQ==">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAABAtMTIzMTIzLjBl",
                    "MTAwMDAw">>}},
        {"i_number_real_pos_overflow.json", <<"WzEyMzEyM2UxMDAwMDBd">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAA8xMjMxMjMuMGUx",
                    "MDAwMDA=">>}},
        {"i_number_real_underflow.json", <<"WzEyM2UtMTAwMDAwMDBd">>, {ok, [0.0]}},
        {"i_number_too_big_neg_int.json", <<"Wy0xMjMxMjMxMjMxMjMxMjMxMjMxMjMx", "MjMxMjMxMjNd">>,
            {ok, [-123123123123123123123123123123]}},
        {"i_number_too_big_pos_int.json", <<"WzEwMDAwMDAwMDAwMDAwMDAwMDAwMF0=">>,
            {ok, [100000000000000000000]}},
        {"i_number_very_big_negative_int.json",
            <<"Wy0yMzc0NjIzNzQ2NzMyNzY4OTQyNzk4", "MzI3NDk4MzI0MjM0Nzk4MjMyNDYzMjc4", "NDZd">>,
            {ok, [-237462374673276894279832749832423479823246327846]}},
        {"i_object_key_lone_2nd_surrogate.json", <<"eyJcdURGQUEiOjB9">>,
            {error, {unexpected_sequence, <<92, 117, 68, 70, 65, 65>>}}},
        {"i_string_1st_surrogate_but_2nd_missing.json", <<"WyJcdURBREEiXQ==">>,
            {error, unexpected_end}},
        {"i_string_1st_valid_surrogate_2nd_invalid.json", <<"WyJcdUQ4ODhcdTEyMzQiXQ==">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAAxcdUQ4ODhcdTEy", "MzQ=">>}},
        {"i_string_UTF-16LE_with_BOM.json", <<"//5bACIA6QAiAF0A">>, {error, {invalid_byte, 255}}},
        {"i_string_UTF-8_invalid_sequence.json", <<"WyLml6XRiPoiXQ==">>,
            {error, {invalid_byte, 250}}},
        {"i_string_UTF8_surrogate_U+D800.json", <<"WyLtoIAiXQ==">>, {error, {invalid_byte, 160}}},
        {"i_string_incomplete_surrogate_and_escape_valid.json", <<"WyJcdUQ4MDBcbiJd">>,
            {error, unexpected_end}},
        {"i_string_incomplete_surrogate_pair.json", <<"WyJcdURkMWVhIl0=">>,
            {error, {unexpected_sequence, <<92, 117, 68, 100, 49, 101>>}}},
        {"i_string_incomplete_surrogates_escape_valid.json", <<"WyJcdUQ4MDBcdUQ4MDBcbiJd">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAAxcdUQ4MDBcdUQ4", "MDA=">>}},
        {"i_string_invalid_lonely_surrogate.json", <<"WyJcdWQ4MDAiXQ==">>, {error, unexpected_end}},
        {"i_string_invalid_surrogate.json", <<"WyJcdWQ4MDBhYmMiXQ==">>, {error, unexpected_end}},
        {"i_string_invalid_utf-8.json", <<"WyL/Il0=">>, {error, {invalid_byte, 255}}},
        {"i_string_inverted_surrogates_U+1D11E.json", <<"WyJcdURkMWVcdUQ4MzQiXQ==">>,
            {error, {unexpected_sequence, <<92, 117, 68, 100, 49, 101>>}}},
        {"i_string_iso_latin_1.json", <<"WyLpIl0=">>, {error, {invalid_byte, 34}}},
        {"i_string_lone_second_surrogate.json", <<"WyJcdURGQUEiXQ==">>,
            {error, {unexpected_sequence, <<92, 117, 68, 70, 65, 65>>}}},
        {"i_string_lone_utf8_continuation_byte.json", <<"WyKBIl0=">>, {error, {invalid_byte, 129}}},
        {"i_string_not_in_unicode_range.json", <<"WyL0v7+/Il0=">>, {error, {invalid_byte, 191}}},
        {"i_string_overlong_sequence_2_bytes.json", <<"WyLAryJd">>, {error, {invalid_byte, 192}}},
        {"i_string_overlong_sequence_6_bytes.json", <<"WyL8g7+/v78iXQ==">>,
            {error, {invalid_byte, 252}}},
        {"i_string_overlong_sequence_6_bytes_null.json", <<"WyL8gICAgIAiXQ==">>,
            {error, {invalid_byte, 252}}},
        {"i_string_truncated-utf-8.json", <<"WyLg/yJd">>, {error, {invalid_byte, 255}}},
        {"i_string_utf16BE_no_BOM.json", <<"AFsAIgDpACIAXQ==">>, {error, {invalid_byte, 0}}},
        {"i_string_utf16LE_no_BOM.json", <<"WwAiAOkAIgBdAA==">>, {error, {invalid_byte, 0}}},
        {"i_structure_500_nested_arrays.json",
            <<"W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb", "W1tbW1tbW1tbW1tbW1tbW1tbW1tbW1tb",
                "W1tbW1tbW1tbW1tbW1tbW1tbW1tdXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d",
                "XV1dXV1dXV1dXV1dXV1dXV1dXV1dXV1d", "XV1dXV1dXV1dXV1dXV1dXQ==">>,
            {external_term,
                <<"g2gCdwJva2wAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA", "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA",
                    "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs", "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB",
                    "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA", "AWwAAAABbAAAAAFsAAAAAWwAAAABbAAA",
                    "AAFsAAAAAWwAAAABbAAAAAFsAAAAAWwA", "AAABbAAAAAFsAAAAAWwAAAABbAAAAAFs",
                    "AAAAAWwAAAABbAAAAAFsAAAAAWwAAAAB", "bAAAAAFsAAAAAWwAAAABbAAAAAFsAAAA",
                    "AWwAAAABampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "ampqampqampqampqampqampqampqampq",
                    "ampqampqampqampqampqampqampqampq", "amo=">>}},
        {"i_structure_UTF-8_BOM_empty_object.json", <<"77u/e30=">>, {error, {invalid_byte, 239}}}
    ].

t_tests() ->
    [
        {"number_-9223372036854775808.json", <<"Wy05MjIzMzcyMDM2ODU0Nzc1ODA4XQo=">>,
            {ok, [-9223372036854775808]}},
        {"number_-9223372036854775809.json", <<"Wy05MjIzMzcyMDM2ODU0Nzc1ODA5XQo=">>,
            {ok, [-9223372036854775809]}},
        {"number_1.0.json", <<"WzEuMF0K">>, {ok, [1.0]}},
        {"number_1.000000000000000005.json", <<"WzEuMDAwMDAwMDAwMDAwMDAwMDA1XQo=">>, {ok, [1.0]}},
        {"number_1000000000000000.json", <<"WzEwMDAwMDAwMDAwMDAwMDBdCg==">>,
            {ok, [1000000000000000]}},
        {"number_10000000000000000999.json", <<"WzEwMDAwMDAwMDAwMDAwMDAwOTk5XQo=">>,
            {ok, [10000000000000000999]}},
        {"number_1e-999.json", <<"WzFFLTk5OV0K">>, {ok, [0.0]}},
        {"number_1e6.json", <<"WzFFNl0K">>, {ok, [1.0e6]}},
        {"number_9223372036854775807.json", <<"WzkyMjMzNzIwMzY4NTQ3NzU4MDddCg==">>,
            {ok, [9223372036854775807]}},
        {"number_9223372036854775808.json", <<"WzkyMjMzNzIwMzY4NTQ3NzU4MDhdCg==">>,
            {ok, [9223372036854775808]}},
        {"object_key_nfc_nfd.json", <<"eyLDqSI6Ik5GQyIsImXMgSI6Ik5GRCJ9">>,
            {external_term, <<"g2gCdwJva3QAAAACbQAAAANlzIFtAAAA", "A05GRG0AAAACw6ltAAAAA05GQw==">>}},
        {"object_key_nfd_nfc.json", <<"eyJlzIEiOiJORkQiLCLDqSI6Ik5GQyJ9">>,
            {external_term, <<"g2gCdwJva3QAAAACbQAAAANlzIFtAAAA", "A05GRG0AAAACw6ltAAAAA05GQw==">>}},
        {"object_same_key_different_values.json", <<"eyJhIjoxLCJhIjoyfQ==">>, {ok, #{<<97>> => 1}}},
        {"object_same_key_same_value.json", <<"eyJhIjoxLCJhIjoxfQ==">>, {ok, #{<<97>> => 1}}},
        {"object_same_key_unclear_values.json", <<"eyJhIjowLCAiYSI6LTB9Cg==">>,
            {ok, #{<<97>> => 0}}},
        {"string_1_escaped_invalid_codepoint.json", <<"WyJcdUQ4MDAiXQ==">>,
            {error, unexpected_end}},
        {"string_1_invalid_codepoint.json", <<"WyLtoIAiXQ==">>, {error, {invalid_byte, 160}}},
        {"string_2_escaped_invalid_codepoints.json", <<"WyJcdUQ4MDBcdUQ4MDAiXQ==">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAAxcdUQ4MDBcdUQ4", "MDA=">>}},
        {"string_2_invalid_codepoints.json", <<"WyLtoIDtoIAiXQ==">>, {error, {invalid_byte, 160}}},
        {"string_3_escaped_invalid_codepoints.json", <<"WyJcdUQ4MDBcdUQ4MDBcdUQ4MDAiXQ==">>,
            {external_term,
                <<"g2gCdwVlcnJvcmgCdxN1bmV4cGVjdGVk", "X3NlcXVlbmNlbQAAAAxcdUQ4MDBcdUQ4", "MDA=">>}},
        {"string_3_invalid_codepoints.json", <<"WyLtoIDtoIDtoIAiXQ==">>,
            {error, {invalid_byte, 160}}},
        {"string_with_escaped_NULL.json", <<"WyJBXHUwMDAwQiJd">>, {ok, [<<65, 0, 66>>]}}
    ].

test_encode_truncated_utf8() ->
    %% Valid truncated UTF-8 sequences must raise unexpected_end (not invalid_byte)
    %% 2-byte lead, no continuation (e.g. start of é = C3 A9)
    ok =
        try json:encode_binary(<<16#C3>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% 3-byte lead alone (e.g. start of – = E2 80 93)
    ok =
        try json:encode_binary(<<16#E2>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% 3-byte lead + 1 continuation (valid prefix)
    ok =
        try json:encode_binary(<<16#E2, 16#80>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% 4-byte lead alone (e.g. start of U+1F600)
    ok =
        try json:encode_binary(<<16#F0>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% 4-byte lead + 1 continuation
    ok =
        try json:encode_binary(<<16#F0, 16#9F>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% 4-byte lead + 2 continuations
    ok =
        try json:encode_binary(<<16#F0, 16#9F, 16#98>>) of
            _ -> error(should_have_failed)
        catch
            error:unexpected_end -> ok
        end,
    %% Truly invalid bytes must still raise {invalid_byte, _}
    ok =
        try json:encode_binary(<<16#FF>>) of
            _ -> error(should_have_failed)
        catch
            error:{invalid_byte, 16#FF} -> ok
        end,
    ok =
        try json:encode_binary(<<16#80>>) of
            _ -> error(should_have_failed)
        catch
            error:{invalid_byte, 16#80} -> ok
        end,
    ok.

test_encode_checked_normalizing_encoder() ->
    %% Custom encoder that uppercases keys — duplicate detection must use
    %% encoded (post-normalization) keys, not raw keys.
    Enc = fun
        (B, _E) when is_binary(B) ->
            json:encode_binary(string:uppercase(B));
        (Other, E) ->
            json:encode_value(Other, E)
    end,
    ?ASSERT_ERROR(
        json:encode_map_checked(#{<<"foo">> => 1, <<"FOO">> => 2}, Enc)
    ),
    ?ASSERT_ERROR(
        json:encode_key_value_list_checked(
            [{<<"foo">>, 1}, {<<"FOO">>, 2}], Enc
        )
    ),
    ok.

test_encode_weather() ->
    NasuMachi = <<16#E9, 16#82, 16#A3, 16#E9, 16#A0, 16#88, 16#E7, 16#94, 16#BA>>,
    Weather = #{
        <<"location">> => #{
            <<"name">> => NasuMachi,
            <<"country">> => <<"JP">>,
            <<"coordinates">> => [140.1209, 37.0198],
            <<"utc_offset">> => 9
        },
        <<"current">> => #{
            <<"temperature">> => 18.5,
            <<"humidity">> => 62,
            <<"conditions">> => [<<"partly_cloudy">>, <<"windy">>],
            <<"wind">> => #{<<"speed">> => 5.2, <<"direction">> => <<"NNW">>},
            <<"precipitation">> => false
        },
        <<"forecast">> => [
            #{
                <<"day">> => 1,
                <<"high">> => 22.0,
                <<"low">> => 12.5,
                <<"rain_probability">> => 0.15
            },
            #{<<"day">> => 2, <<"high">> => 19.0, <<"low">> => 10.0, <<"rain_probability">> => 0.80}
        ],
        <<"alerts">> => null
    },
    Encoded = to_bin(json:encode(Weather)),
    Decoded = json:decode(Encoded),

    Location = maps:get(<<"location">>, Decoded),
    NasuMachi = maps:get(<<"name">>, Location),
    <<"JP">> = maps:get(<<"country">>, Location),
    [140.1209, 37.0198] = maps:get(<<"coordinates">>, Location),
    9 = maps:get(<<"utc_offset">>, Location),

    Current = maps:get(<<"current">>, Decoded),
    ?ASSERT_EQUALS(18.5, maps:get(<<"temperature">>, Current)),
    62 = maps:get(<<"humidity">>, Current),
    [<<"partly_cloudy">>, <<"windy">>] = maps:get(<<"conditions">>, Current),
    ?ASSERT_EQUALS(5.2, maps:get(<<"speed">>, maps:get(<<"wind">>, Current))),
    <<"NNW">> = maps:get(<<"direction">>, maps:get(<<"wind">>, Current)),
    false = maps:get(<<"precipitation">>, Current),

    [Day1, Day2] = maps:get(<<"forecast">>, Decoded),
    1 = maps:get(<<"day">>, Day1),
    ?ASSERT_EQUALS(22.0, maps:get(<<"high">>, Day1)),
    ?ASSERT_EQUALS(12.5, maps:get(<<"low">>, Day1)),
    ?ASSERT_EQUALS(0.15, maps:get(<<"rain_probability">>, Day1)),
    2 = maps:get(<<"day">>, Day2),
    ?ASSERT_EQUALS(0.80, maps:get(<<"rain_probability">>, Day2)),

    null = maps:get(<<"alerts">>, Decoded),
    ok.
