/*
 * This file is part of AtomVM.
 *
 * Copyright 2019 Davide Bettio <davide@uninstall.it>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
 */

#ifndef _PLATFORM_DEFAULTATOMS_H_
#define _PLATFORM_DEFAULTATOMS_H_

#include "defaultatoms.h"

#define READ_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 0)
#define GPIO_INTERRUPT_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 1)
#define RISING_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 2)
#define FALLING_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 3)
#define BOTH_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 4)
#define LOW_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 5)
#define HIGH_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 6)

#define ESP32_ATOM_INDEX (PLATFORM_ATOMS_BASE_INDEX + 7)

#define NETWORK_ATOMS_BASE_INDEX (PLATFORM_ATOMS_BASE_INDEX + 8)
#define STA_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 0)
#define SSID_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 1)
#define PSK_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 2)
#define SNTP_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 3)
#define STA_GOT_IP_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 4)
#define STA_CONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 5)
#define STA_DISCONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 6)
#define STA_DHCP_HOSTNAME_INDEX (NETWORK_ATOMS_BASE_INDEX + 7)
#define AP_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 8)
#define SSID_HIDDEN_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 9)
#define MAX_CONNECTIONS_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 10)
#define AP_STARTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 11)
#define AP_STA_CONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 12)
#define AP_STA_DISCONNECTED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 13)
#define AP_STA_IP_ASSIGNED_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 14)
#define HOST_ATOM_INDEX (NETWORK_ATOMS_BASE_INDEX + 15)

#define SPIDRIVER_ATOMS_BASE_INDEX (NETWORK_ATOMS_BASE_INDEX + 16)
#define BUS_CONFIG_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 0)
#define MISO_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 1)
#define MOSI_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 2)
#define SCLK_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 3)
#define SPI_PERIPHERAL_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 4)
#define HSPI_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 5)
#define VSPI_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 6)
#define DEVICE_CONFIG_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 7)
#define SPI_CLOCK_HZ_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 8)
#define SPI_MODE_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 9)
#define SPI_CS_IO_NUM_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 10)
#define ADDRESS_LEN_BITS_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 11)
#define COMMAND_LEN_BITS_ATOM_INDEX (SPIDRIVER_ATOMS_BASE_INDEX + 12)

#define UART_ATOMS_BASE_INDEX (COMMAND_LEN_BITS_ATOM_INDEX + 1)
#define NAME_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 0)
#define SPEED_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 1)
#define WRITE_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 2)
#define DATA_BITS_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 3)
#define STOP_BITS_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 4)
#define FLOW_CONTROL_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 5)
#define PARITY_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 6)
#define TX_PIN_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 7)
#define RX_PIN_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 8)
#define RTS_PIN_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 9)
#define CTS_PIN_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 10)
#define DEFAULT_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 11)
#define EVENT_QUEUE_LEN_ATOM_INDEX (UART_ATOMS_BASE_INDEX + 12)

#define READ_ATOM TERM_FROM_ATOM_INDEX(READ_ATOM_INDEX)
#define GPIO_INTERRUPT_ATOM TERM_FROM_ATOM_INDEX(GPIO_INTERRUPT_ATOM_INDEX)
#define RISING_ATOM TERM_FROM_ATOM_INDEX(RISING_ATOM_INDEX)
#define FALLING_ATOM TERM_FROM_ATOM_INDEX(FALLING_ATOM_INDEX)
#define BOTH_ATOM TERM_FROM_ATOM_INDEX(BOTH_ATOM_INDEX)
#define LOW_ATOM TERM_FROM_ATOM_INDEX(LOW_ATOM_INDEX)
#define HIGH_ATOM TERM_FROM_ATOM_INDEX(HIGH_ATOM_INDEX)

#define ESP32_ATOM TERM_FROM_ATOM_INDEX(ESP32_ATOM_INDEX)

// network
#define STA_ATOM TERM_FROM_ATOM_INDEX(STA_ATOM_INDEX)
#define SSID_ATOM TERM_FROM_ATOM_INDEX(SSID_ATOM_INDEX)
#define PSK_ATOM TERM_FROM_ATOM_INDEX(PSK_ATOM_INDEX)
#define SNTP_ATOM TERM_FROM_ATOM_INDEX(SNTP_ATOM_INDEX)
#define STA_GOT_IP_ATOM TERM_FROM_ATOM_INDEX(STA_GOT_IP_ATOM_INDEX)
#define STA_CONNECTED_ATOM TERM_FROM_ATOM_INDEX(STA_CONNECTED_ATOM_INDEX)
#define STA_DISCONNECTED_ATOM TERM_FROM_ATOM_INDEX(STA_DISCONNECTED_ATOM_INDEX)
#define STA_DHCP_HOSTNAME_ATOM TERM_FROM_ATOM_INDEX(STA_DHCP_HOSTNAME_INDEX)
#define AP_ATOM TERM_FROM_ATOM_INDEX(AP_ATOM_INDEX)
#define SSID_HIDDEN_ATOM TERM_FROM_ATOM_INDEX(SSID_HIDDEN_ATOM_INDEX)
#define MAX_CONNECTIONS_ATOM TERM_FROM_ATOM_INDEX(MAX_CONNECTIONS_ATOM_INDEX)
#define AP_STARTED_ATOM TERM_FROM_ATOM_INDEX(AP_STARTED_ATOM_INDEX)
#define AP_STA_CONNECTED_ATOM TERM_FROM_ATOM_INDEX(AP_STA_CONNECTED_ATOM_INDEX)
#define AP_STA_DISCONNECTED_ATOM TERM_FROM_ATOM_INDEX(AP_STA_DISCONNECTED_ATOM_INDEX)
#define AP_STA_IP_ASSIGNED_ATOM TERM_FROM_ATOM_INDEX(AP_STA_IP_ASSIGNED_ATOM_INDEX)
#define HOST_ATOM TERM_FROM_ATOM_INDEX(HOST_ATOM_INDEX)

// spidriver
#define BUS_CONFIG_ATOM TERM_FROM_ATOM_INDEX(BUS_CONFIG_ATOM_INDEX)
#define MISO_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(MISO_IO_NUM_ATOM_INDEX)
#define MOSI_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(MOSI_IO_NUM_ATOM_INDEX)
#define SCLK_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SCLK_IO_NUM_ATOM_INDEX)
#define SPI_PERIPHERAL_ATOM TERM_FROM_ATOM_INDEX(SPI_PERIPHERAL_ATOM_INDEX)
#define HSPI_ATOM TERM_FROM_ATOM_INDEX(HSPI_ATOM_INDEX)
#define VSPI_ATOM TERM_FROM_ATOM_INDEX(VSPI_ATOM_INDEX)
#define DEVICE_CONFIG_ATOM TERM_FROM_ATOM_INDEX(DEVICE_CONFIG_ATOM_INDEX)
#define SPI_CLOCK_HZ_ATOM TERM_FROM_ATOM_INDEX(SPI_CLOCK_HZ_ATOM_INDEX)
#define SPI_MODE_ATOM TERM_FROM_ATOM_INDEX(SPI_MODE_ATOM_INDEX)
#define SPI_CS_IO_NUM_ATOM TERM_FROM_ATOM_INDEX(SPI_CS_IO_NUM_ATOM_INDEX)
#define ADDRESS_LEN_BITS_ATOM TERM_FROM_ATOM_INDEX(ADDRESS_LEN_BITS_ATOM_INDEX)
#define COMMAND_LEN_BITS_ATOM TERM_FROM_ATOM_INDEX(COMMAND_LEN_BITS_ATOM_INDEX)

// uart_driver
#define NAME_ATOM TERM_FROM_ATOM_INDEX(NAME_ATOM_INDEX)
#define SPEED_ATOM TERM_FROM_ATOM_INDEX(SPEED_ATOM_INDEX)
#define WRITE_ATOM TERM_FROM_ATOM_INDEX(WRITE_ATOM_INDEX)
#define DATA_BITS_ATOM TERM_FROM_ATOM_INDEX(DATA_BITS_ATOM_INDEX)
#define STOP_BITS_ATOM TERM_FROM_ATOM_INDEX(STOP_BITS_ATOM_INDEX)
#define FLOW_CONTROL_ATOM TERM_FROM_ATOM_INDEX(FLOW_CONTROL_ATOM_INDEX)
#define PARITY_ATOM TERM_FROM_ATOM_INDEX(PARITY_ATOM_INDEX)
#define TX_PIN_ATOM TERM_FROM_ATOM_INDEX(TX_PIN_ATOM_INDEX)
#define RX_PIN_ATOM TERM_FROM_ATOM_INDEX(RX_PIN_ATOM_INDEX)
#define RTS_PIN_ATOM TERM_FROM_ATOM_INDEX(RTS_PIN_ATOM_INDEX)
#define CTS_PIN_ATOM TERM_FROM_ATOM_INDEX(CTS_PIN_ATOM_INDEX)
#define DEFAULT_ATOM TERM_FROM_ATOM_INDEX(DEFAULT_ATOM_INDEX)
#define EVENT_QUEUE_LEN_ATOM TERM_FROM_ATOM_INDEX(EVENT_QUEUE_LEN_ATOM_INDEX)

#endif
