#
#  Copyright 2017-2023 Davide Bettio <davide@uninstall.it>
#
#  SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later
#

name: Build Libraries

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  build-libraries:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        mbedtls: ["default", "mbedtls@4"]

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: erlef/setup-beam@v1
      with:
        otp-version: "28"
        elixir-version: "1.19"
        rebar3-version: "3.25.1"
        gleam-version: "1.15.2"
        hexpm-mirrors: |
          https://builds.hex.pm
          https://repo.hex.pm
          https://cdn.jsdelivr.net/hex

    - name: "APT update"
      run: sudo apt update -y

    - name: "Install deps"
      run: |
        sudo apt install -y build-essential cmake gperf zlib1g-dev
        if [[ "${{ matrix.mbedtls }}" == "default" ]]; then
            sudo apt install -y libmbedtls-dev
        fi
        # Get a more recent valgrind
        sudo snap install valgrind --classic

    - name: "Install specific MbedTLS version"
      if: matrix.mbedtls == 'mbedtls@4'
      run: |
        git clone --depth 1 --branch mbedtls-4.0.0 --recurse-submodules https://github.com/Mbed-TLS/mbedtls
        cd mbedtls
        mkdir build
        cd build
        cmake -DENABLE_TESTING=OFF -DUSE_SHARED_MBEDTLS_LIBRARY=On -DCMAKE_INSTALL_PREFIX=/usr/local ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        echo "MBEDTLS_ROOT_DIR=/usr/local" >> $GITHUB_ENV

    # Builder info
    - name: "System info"
      run: |
        echo "**uname:**"
        uname -a
        echo "**libc version:**"
        ldd --version
        echo "**C Compiler version:**"
        cc --version
        c++ --version
        echo "**Linker version:**"
        ld --version
        echo "**CMake version:**"
        cmake --version
        echo "**OTP version:**"
        cat $(dirname $(which erlc))/../releases/RELEASES || true

    # Build
    - name: "Build: create build dir"
      run: mkdir build

    - name: "Build: run cmake"
      working-directory: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${MBEDTLS_ROOT_DIR:+-DMBEDTLS_ROOT_DIR=$MBEDTLS_ROOT_DIR} ..

    - name: "Build: run make"
      working-directory: build
      run: make

    - name: "Build: run dialyzer"
      working-directory: build
      run: make dialyzer

    - name: "Test: test_alisp.avm with valgrind"
      timeout-minutes: 5
      working-directory: build
      run: |
        valgrind --error-exitcode=1 ./src/AtomVM ./tests/libs/etest/test_alisp.avm

    - name: "Test: test_alisp.avm"
      timeout-minutes: 5
      working-directory: build
      run: |
        ./src/AtomVM ./tests/libs/etest/test_alisp.avm

    - name: "Test: test_etest.avm with valgrind"
      timeout-minutes: 5
      working-directory: build
      run: |
        valgrind --error-exitcode=1 ./src/AtomVM ./tests/libs/etest/test_etest.avm

    - name: "Test: test_etest.avm"
      timeout-minutes: 5
      working-directory: build
      run: |
        ./src/AtomVM ./tests/libs/etest/test_etest.avm

    - name: "Test: test_estdlib.avm with valgrind"
      timeout-minutes: 10
      working-directory: build
      run: |
        valgrind --error-exitcode=1 ./src/AtomVM ./tests/libs/estdlib/test_estdlib.avm

    - name: "Test: test_estdlib.avm"
      timeout-minutes: 10
      working-directory: build
      run: |
        ./src/AtomVM ./tests/libs/estdlib/test_estdlib.avm

    - name: "Rename and write sha256sum"
      working-directory: build
      run: |
        for variant in atomvmlib atomvmlib-esp32 atomvmlib-rp2 atomvmlib-stm32 atomvmlib-emscripten; do
          VARIANT_FILE="${variant}-${{ github.ref_name }}.avm"
          mv "libs/${variant}.avm" "libs/${VARIANT_FILE}" &&
          sha256sum "libs/${VARIANT_FILE}" > "libs/${VARIANT_FILE}.sha256"
        done
        HELLO_WORLD_FILE=hello_world-${{ github.ref_name }}.avm
        mv examples/erlang/hello_world.avm "examples/erlang/${HELLO_WORLD_FILE}"
        sha256sum "examples/erlang/${HELLO_WORLD_FILE}" > "examples/erlang/${HELLO_WORLD_FILE}.sha256"

    - name: Release
      uses: softprops/action-gh-release@v3.0.0
      if: startsWith(github.ref, 'refs/tags/') && matrix.mbedtls == 'default'
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          build/libs/atomvmlib-${{ github.ref_name }}.avm
          build/libs/atomvmlib-${{ github.ref_name }}.avm.sha256
          build/libs/atomvmlib-esp32-${{ github.ref_name }}.avm
          build/libs/atomvmlib-esp32-${{ github.ref_name }}.avm.sha256
          build/libs/atomvmlib-rp2-${{ github.ref_name }}.avm
          build/libs/atomvmlib-rp2-${{ github.ref_name }}.avm.sha256
          build/libs/atomvmlib-stm32-${{ github.ref_name }}.avm
          build/libs/atomvmlib-stm32-${{ github.ref_name }}.avm.sha256
          build/libs/atomvmlib-emscripten-${{ github.ref_name }}.avm
          build/libs/atomvmlib-emscripten-${{ github.ref_name }}.avm.sha256
          build/examples/erlang/hello_world-${{ github.ref_name }}.avm
          build/examples/erlang/hello_world-${{ github.ref_name }}.avm.sha256
